In [122]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\python\envs\opencv\lib\site-packages (3.0.10)
Requirement already satisfied: et-xmlfile in c:\python\envs\opencv\lib\site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [123]:
import pandas as pd
import openpyxl

In [124]:
speed = pd.read_excel('./서울시 도로별 통행속도.xlsx')
speed

,일자,요일,도로명,링크아이디,시점명,종점명,방향,거리,차선수,기능유형구분,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,20221001,토,4.19로,1080012200,아카데미하우스,국립4.19묘지,상행,1179,1.0,보조간선도로,...,31.67,25.39,38.09,26.85,32.53,29.62,36.04,36.27,43.47,46.73
1,20221001,토,4.19로,1080012800,국립4.19묘지,국립4.19묘지입구,상행,352,2.0,보조간선도로,...,11.52,12.73,11.51,11.60,13.69,13.42,17.34,18.93,15.52,19.17
2,20221001,토,4.19로,1080012700,국립4.19묘지입구,국립4.19묘지,하행,354,2.0,보조간선도로,...,20.02,16.59,18.50,18.84,17.25,16.51,19.54,19.05,21.07,24.90
3,20221001,토,4.19로,1080012100,국립4.19묘지,아카데미하우스,하행,1190,1.0,보조간선도로,...,43.06,43.53,61.53,60.40,47.24,49.73,45.53,48.78,50.48,39.41
4,20221001,토,가락로,1230024700,방이초교,방이동고분군,상행,844,1.0,기타도로,...,16.59,16.04,12.86,11.04,12.48,12.66,15.40,15.53,16.44,25.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156806,20221031,월,흑석로,1190003703,중앙대학교,성심의집,하행,398,0.0,기타도로,...,16.56,13.28,13.93,11.02,7.00,9.36,15.43,15.54,15.23,16.45
156807,20221031,월,흑석로,1190003702,성심의집,이화빌라,하행,143,0.0,기타도로,...,17.90,15.41,17.85,13.64,17.25,21.83,20.56,16.79,17.55,22.38
156808,20221031,월,흑석로,1190003701,이화빌라,이화약국,하행,133,0.0,기타도로,...,18.28,19.30,22.20,19.90,19.53,23.68,20.29,17.09,19.60,26.56
156809,20221031,월,희우정로,1130016400,망원정사거리,한강공원입구,상행,692,2.0,기타도로,...,18.45,22.79,23.27,21.78,20.38,19.21,17.62,22.32,22.53,21.99
156810,20221031,월,희우정로,1130016300,한강공원입구,망원정사거리,하행,688,2.0,기타도로,...,15.92,12.50,17.47,19.30,17.96,30.01,16.04,20.39,21.94,29.51

In [125]:
speed.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156811 entries, 0 to 156810
Data columns (total 36 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   일자       156811 non-null  int64
 1   요일       156811 non-null  object
 2   도로명      156811 non-null  object
 3   링크아이디    156811 non-null  int64
 4   시점명      156718 non-null  object
 5   종점명      156718 non-null  object
 6   방향       156811 non-null  object
 7   거리       156811 non-null  int64
 8   차선수      156005 non-null  float64
 9   기능유형구분   156811 non-null  object
 10  도심/외곽구분  156811 non-null  object
 11  권역구분     156811 non-null  object
 12  01시      156772 non-null  float64
 13  02시      156772 non-null  float64
 14  03시      156772 non-null  float64
 15  04시      156764 non-null  float64
 16  05시      156767 non-null  float64
 17  06시      156773 non-null  float64
 18  07시      156775 non-null  float64
 19  08시      156780 non-null  float64
 20  09시      156730 non-null  float64
 21  10시      156724 non-null  float64
 22  11시      156698 non-null  float64
 23  12시      156681 non-null  float64
 24  13시      156676 non-null  float64
 25  14시      156687 non-null  float64
 26  15시      156642 non-null  float64
 27  16시      156646 non-null  float64
 28  17시      156643 non-null  float64
 29  18시      156720 non-null  float64
 30  19시      156724 non-null  float64
 31  20시      156724 non-null  float64
 32  21시      156724 non-null  float64
 33  22시      156766 non-null  float64
 34  23시      156784 non-null  float64
 35  24시      156784 non-null  float64
dtypes: float64(25), int64(3), object(8)
memory usage: 43.1+ MB

In [126]:
speed_2022_10_01 = speed[speed['일자'].isin([20221001])]

In [127]:
speed_2022_10_01.to_csv("./2022_speed.csv")

In [128]:
speed_2022_10_01

,일자,요일,도로명,링크아이디,시점명,종점명,방향,거리,차선수,기능유형구분,...,15시,16시,17시,18시,19시,20시,21시,22시,23시,24시
0,20221001,토,4.19로,1080012200,아카데미하우스,국립4.19묘지,상행,1179,1.0,보조간선도로,...,31.67,25.39,38.09,26.85,32.53,29.62,36.04,36.27,43.47,46.73
1,20221001,토,4.19로,1080012800,국립4.19묘지,국립4.19묘지입구,상행,352,2.0,보조간선도로,...,11.52,12.73,11.51,11.60,13.69,13.42,17.34,18.93,15.52,19.17
2,20221001,토,4.19로,1080012700,국립4.19묘지입구,국립4.19묘지,하행,354,2.0,보조간선도로,...,20.02,16.59,18.50,18.84,17.25,16.51,19.54,19.05,21.07,24.90
3,20221001,토,4.19로,1080012100,국립4.19묘지,아카데미하우스,하행,1190,1.0,보조간선도로,...,43.06,43.53,61.53,60.40,47.24,49.73,45.53,48.78,50.48,39.41
4,20221001,토,가락로,1230024700,방이초교,방이동고분군,상행,844,1.0,기타도로,...,16.59,16.04,12.86,11.04,12.48,12.66,15.40,15.53,16.44,25.23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5054,20221001,토,흑석로,1190003703,중앙대학교,성심의집,하행,398,0.0,기타도로,...,16.04,15.41,15.68,16.59,16.51,15.51,16.68,22.93,20.46,18.67
5055,20221001,토,흑석로,1190003702,성심의집,이화빌라,하행,143,0.0,기타도로,...,19.79,19.41,20.81,18.92,18.50,22.24,20.45,17.17,20.30,20.78
5056,20221001,토,흑석로,1190003701,이화빌라,이화약국,하행,133,0.0,기타도로,...,20.35,20.26,21.33,21.59,20.87,23.95,21.02,20.18,22.74,22.73
5057,20221001,토,희우정로,1130016400,망원정사거리,한강공원입구,상행,692,2.0,기타도로,...,21.74,20.61,19.40,19.02,20.81,18.34,17.62,22.85,18.98,19.60
5058,20221001,토,희우정로,1130016300,한강공원입구,망원정사거리,하행,688,2.0,기타도로,...,15.63,18.56,14.64,15.19,17.73,16.62,14.84,13.23,14.48,20.23

In [129]:
speed_location = speed_2022_10_01[["도로명", "시점명", "종점명"]]

In [130]:
speed_location

        도로명         시점명         종점명
0     4.19로     아카데미하우스    국립4.19묘지
1     4.19로    국립4.19묘지  국립4.19묘지입구
2     4.19로  국립4.19묘지입구    국립4.19묘지
3     4.19로    국립4.19묘지     아카데미하우스
4       가락로        방이초교      방이동고분군
...     ...         ...         ...
5054    흑석로       중앙대학교        성심의집
5055    흑석로        성심의집        이화빌라
5056    흑석로        이화빌라        이화약국
5057   희우정로      망원정사거리      한강공원입구
5058   희우정로      한강공원입구      망원정사거리

[5059 rows x 3 columns]

In [131]:
speed_location["시점 주소"] = speed_location["도로명"] +" " + speed_location["시점명"]
speed_location["종점 주소"] = speed_location["도로명"] +" " + speed_location["종점명"]
speed_location

C:\Users\김두엽\AppData\Local\Temp\ipykernel_35636\2228778383.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  speed_location["시점 주소"] = speed_location["도로명"] +" " + speed_location["시점명"]
C:\Users\김두엽\AppData\Local\Temp\ipykernel_35636\2228778383.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  speed_location["종점 주소"] = speed_location["도로명"] +" " + speed_location["종점명"]

        도로명         시점명         종점명             시점 주소             종점 주소
0     4.19로     아카데미하우스    국립4.19묘지     4.19로 아카데미하우스    4.19로 국립4.19묘지
1     4.19로    국립4.19묘지  국립4.19묘지입구    4.19로 국립4.19묘지  4.19로 국립4.19묘지입구
2     4.19로  국립4.19묘지입구    국립4.19묘지  4.19로 국립4.19묘지입구    4.19로 국립4.19묘지
3     4.19로    국립4.19묘지     아카데미하우스    4.19로 국립4.19묘지     4.19로 아카데미하우스
4       가락로        방이초교      방이동고분군          가락로 방이초교        가락로 방이동고분군
...     ...         ...         ...               ...               ...
5054    흑석로       중앙대학교        성심의집         흑석로 중앙대학교          흑석로 성심의집
5055    흑석로        성심의집        이화빌라          흑석로 성심의집          흑석로 이화빌라
5056    흑석로        이화빌라        이화약국          흑석로 이화빌라          흑석로 이화약국
5057   희우정로      망원정사거리      한강공원입구       희우정로 망원정사거리       희우정로 한강공원입구
5058   희우정로      한강공원입구      망원정사거리       희우정로 한강공원입구       희우정로 망원정사거리

[5059 rows x 5 columns]

In [132]:
speed_location_list = speed_location["시점 주소"].to_list()

In [133]:
speed_location_list_2 = speed_location["종점 주소"].to_list()

In [134]:
len(speed_location_list)

5059

In [135]:
len(speed_location_list_2)

5059

# 분명 위도 경도 계산했을때 거리가 너무먼 자료가 나올거란 말이지. 그거 처리해줘야함

In [136]:
speed_location_list_sum = speed_location_list + speed_location_list_2
len(speed_location_list_sum)

10118

In [137]:
speed_location_list_final = list(set(speed_location_list_sum))
len(speed_location_list_final)

3135

## 3135개?? 뭐지? 겹치는게 있다는 소리인데 잠시만 다시 원본파일로 가보겠음.

In [138]:
len(speed_location)

5059

In [139]:
speed_location_temp = speed_location.drop_duplicates(['시점 주소'])
speed_location_temp

        도로명           시점명         종점명             시점 주소             종점 주소
0     4.19로       아카데미하우스    국립4.19묘지     4.19로 아카데미하우스    4.19로 국립4.19묘지
1     4.19로      국립4.19묘지  국립4.19묘지입구    4.19로 국립4.19묘지  4.19로 국립4.19묘지입구
2     4.19로    국립4.19묘지입구    국립4.19묘지  4.19로 국립4.19묘지입구    4.19로 국립4.19묘지
4       가락로          방이초교      방이동고분군          가락로 방이초교        가락로 방이동고분군
5       가락로        방이동고분군     송파한양아파트        가락로 방이동고분군       가락로 송파한양아파트
...     ...           ...         ...               ...               ...
5048    흑석로  흑석2동신한은행_흑석로        한신빌딩  흑석로 흑석2동신한은행_흑석로          흑석로 한신빌딩
5049    흑석로          한신빌딩         흑석역          흑석로 한신빌딩           흑석로 흑석역
5050    흑석로           흑석역        한신빌딩           흑석로 흑석역          흑석로 한신빌딩
5057   희우정로        망원정사거리      한강공원입구       희우정로 망원정사거리       희우정로 한강공원입구
5058   희우정로        한강공원입구      망원정사거리       희우정로 한강공원입구       희우정로 망원정사거리

[3105 rows x 5 columns]

# 계산량이 줄었으니 개이득~!

In [140]:
speed_location_list_final

['남부순환로 난곡사거리',
 nan,
 '한강대로 용산역앞',
 '가양대로 구룡삼거리',
 '삼일대로 안국역',
 '삼전로 잠실3삼거리',
 '월계로 북서울꿈의숲',
 '광평로 일원역',
 '한천로 장위사거리',
 '아리수로50길 묘곡초교',
 '바우뫼로 영동2교교차로',
 '여의서로 의원회관앞',
 '긴고랑로 중곡1동사거리',
 '종암로 미아사거리',
 '영등포로 관악고교',
 '난계로 논골사거리',
 '소월로2길 후암삼거리',
 '목동동로 목동10-12단지',
 '문정로 문정시영아파트',
 '목동서로 SBS방송센터',
 '송파대로 석촌역',
 '남부순환로 양재전화국',
 '공원로 구로거리공원서',
 '원효로 원효로진출입(강변북로)',
 '서초중앙로 서울교대',
 '논현로 강남을지병원',
 '시루봉로 신동아아파트',
 '화랑로 돌곶이역',
 '방학로 신한은행방학지점',
 '우면산로 선암IC과천방향합류',
 '남부순환로 남부순환로탄천IC진입',
 '무교로 종로구청입구',
 '백제고분로 종합운동장',
 '진흥로 신영동삼거리',
 '등촌로 등촌역',
 '양천로 양화교',
 '가좌로 새절역',
 '디지털로 디지털3단지',
 '고산자로 성수대교북단',
 '마포대로 마포역',
 '중대로 광평교',
 '동작대로 이수교차로',
 '중앙로 계남공원',
 '오목로 목동산돌교회',
 '세종대로 청계광장',
 '능동로 청담대교북단',
 '화랑로 갈매교차로',
 '한글비석로 청원초교',
 '영중로 영등포역',
 '금낭화로 방화119안전센터',
 '상봉로 중화중학교',
 '올림픽로 몽촌토성역',
 '황물로 신답육교',
 '광평로 수서역',
 '남대문로 을지로1가',
 '성덕정길 영동대교북단고가차도',
 '양재대로 삼성서울병원',
 '올림픽대로 여의상류IC',
 '양재대로 명덕초교',
 '화랑로 종암사거리',
 '잠실로 KT송파지사',
 '토정로 마포역',
 '석촌호수로 방이삼거리',
 '진황도로 길동사거리앞',
 '역말로 역촌사거리',
 '개화동로 개화사거리',
 '공릉로 중원중학교',
 '의사당대로 여의도역',
 '신월여의지하도로 신월요금소',
 '한강대로 숙대입구역',
 '월드컵북로 월드컵파크12단지',
 '동일로243길 수락산역',
 '이태원로 녹사평역',
 '수색로 증산교',
 '성수이로 성수역',
 '목동서로 CBS방송국',
 '증산로 월드컵공원',
 '노들로 서울교남단',
 '경부고속도로 경부고속도로(만남의광장)',
 '망우로 동1로지하차도',
 '삼학사로 배명사거리',
 '금낭화로 방화5단지교차로',
 '삼성로 청담사거리',
 '가로공원로76길 화곡대림아파트',
 '우이천로 월계주유소',
 '노들로 여의하류IC',
 '소파로 도동삼거리',
 '창경궁로 종로4가',
 '소월로 버티고개삼거리',
 '공릉로 북부검찰청입구',
 '회기로5길 월곡역입구',
 '덕릉로 당고개입구오거리',
 '세검정로 세검정',
 '동부간선도로 광진구-성동구경계(5)',
 '동일로213길 상계백병원',
 '목동서로 오목공원',
 '올림픽대로 올림픽대로 서울강동-경기하남',
 '강변북로 이촌대림아파트(강변북로)',
 '대림로 성원아파트앞',
 '고덕로 고덕역',
 '당산로 당서초교',
 '경인로 오류동삼거리',
 '동산로 양일초등학교',
 '양화로 홍대입구역',
 '여의동로 여의교',
 '노원로 상계초교',
 '가양대로 월드컵파크7단지',
 '수유로 만능카종합공업사',
 '양천로 방화사거리',
 '성암로 DMC첨단산업센터',
 '남부순환로 우면삼거리',
 '고산자로 동대문구청',
 '도당로 삼익세라믹아파트',
 '홍제천로 홍연2교동측',
 '뚝섬로 성수대교북단교차로',
 '석계로 광운대역',
 '구로중앙로 오금교동측',
 '신내로 중화초교',
 '화랑로 태릉입구역',
 '강남대로 교보타워사거리',
 '금낭화로 방신종합시장입구',
 '동부간선도로 동부간선도로-일반국도6호선램프',
 '은평로 신사동고개사거리',
 '덕릉로 수유사거리',
 '녹사평대로 재정관리단앞',
 '상계로 상계역',
 '봉은사로 차관아파트',
 '정릉로 봉국사',
 '노해로 이마트',
 '위례성대로 올림픽공원남4문',
 '창경궁로 한성대입구역',
 '학동로 강남구청역',
 '우정국로 종로1가',
 '대학로 이화사거리',
 '우이천로 우이교',
 '올림픽로 서울종합운동장',
 '안양천로 목동체육공원',
 '홍릉로 청량리역',
 '강남대로 강남역',
 '문성로 신림1교',
 '남부순환로 안양교',
 '봉천로 구로디지털단지역',
 '강서로 화곡사거리',
 '우이천로 초안교',
 '망우로21길 회기역(2번출구)',
 '잠원로 고속터미널',
 '도당로 방학동새마을금고',
 '서오릉로 역촌사거리',
 '천호대로 상일IC서측',
 '성산로 마포구청역',
 '삼학사로1길 배명고교',
 '서강로 신촌로터리',
 '종암로 서울사대부고앞',
 '동부간선도로 성동JC',
 '새문안로3길 용비어천가',
 '선유로 양남사거리',
 '방학로 서울문화고교',
 '독막로 마포우체국',
 '도산대로 강남을지병원',
 '율곡로 안국동사거리',
 '북악산로 북악골프연습장',
 '내부순환로 월곡램프(내부순환로)',
 '구리암사대교 암사IC(북측)',
 '상일로 주공6단지',
 '성산로 사천교동측',
 '장월로 정외과의원',
 '이촌로 신용산초교',
 '덕릉로 화계유치원',
 '정릉로 국민대학교앞',
 '창경궁로 중구청',
 '동일로 상계14-16단지',
 '경인로 삼천리아파트',
 '부일로 부일로부천시계',
 '홍릉로 영휘원',
 '상암산로 상암월드컵4단지',
 '가양대로 수색교',
 '올림픽대로 방화대교남단(88JC)',
 '수색로 수색역',
 '겸재로 면목사거리',
 '응암로 북가좌삼거리',
 '광나루로 성수중고교',
 '백제고분로 석촌역',
 '상암로 굽은다리역',
 '테헤란로115길 삼성교서측',
 '수색로 수색교',
 '남부순환로 양재역',
 '통일로 동명여고',
 '오금로 거여동사거리',
 '당산로 문래공원',
 '회기로 경희대학교앞',
 '오목로 오목지하차도(서단)',
 '발산로 외발산사거리',
 '강변북로 노을공원',
 '왕산로 성바오로병원',
 '응암로 응암시장',
 '북부간선도로 종암JC',
 '목동서로 양천소방서',
 '목동동로 방송회관',
 '봉은사로 선정릉역',
 '강동대로 서하남IC입구',
 '서울시립대로 전농1동',
 '월드컵로 성산초교앞',
 '테헤란로 강남경찰서',
 '개포로 대청초교',
 '서운로 서초삼호아파트',
 '양천로27길 정곡초교',
 '진황도로 방아삼거리',
 '개포로 대청역',
 '여의공원로 동아일보하단',
 '응암로 북가좌사거리',
 '통일로 연신내역',
 '섬밭로 한천교동측',
 '동부간선도로 동부간선도로-강변북로램프(16)',
 '동산로 신진빌딩',
 '올림픽로 암사역',
 '통일로 독립문역',
 '경인고속도로 목동지하차도(서측)',
 '새문안로5길 정부중앙청사별관',
 '인수봉로 국립4.19묘지',
 '강변북로 한강대교북단',
 '광나루로 상원삼거리',
 '올림픽대로 천호대교남단',
 '이문로 시조사삼거리',
 '백련산로 응암제2동주민센터',
 '만리재로 만리시장',
 '개화동로 행주대교고양시계',
 '송이로 문정동현대아파트',
 '마방로 영동1교남단',
 '반포대로 예술의전당',
 '사직로 사직공원',
 '화곡로 가양아파트',
 '북촌로 안국역',
 '뚝섬로 뚝도시장',
 '새창로 도원삼성래미안아파트',
 '천중로 천일초교',
 '혜화로 성북초교앞',
 '고덕로80길 상일주공5단지',
 '남대문로7길 명동입구',
 '석촌호수로 석촌호(서호)',
 '을지로 을지로1가',
 '지봉로 청계7가',
 '진흥로 대조불광시장',
 '남대문로7길 웨스턴조선호텔',
 '경인고속도로 신월IC서측(남부순환로양재진출)',
 '송파대로 석촌호수(롯데월드)',
 '솔샘로 삼양동사거리',
 '강남순환로 서초터널출구부',
 '상도로 숭실대입구역',
 '백범로 서강대앞',
 '화랑로 북부검찰청입구',
 '와우산로 산울림소극장',
 '송파대로60길 잠실철교남단',
 '개포로 개포동역',
 '가락로 방이동고분군',
 '상암로61길 고덕삼환아파트',
 '신풍로 대영초교',
 '동부간선도로 군자교분기점',
 '내부순환로 홍제램프(내부순환로)',
 '남대문로 한국은행앞',
 '아차산로 자양사거리',
 '상암산로 상암월드컵아파트',
 '여의나루로 여의중고교앞',
 '압구정로 청담사거리',
 '위례성대로 몽촌토성역',
 '목동중앙로 신목중학교',
 '원효로 원효동산호아파트',
 '원효로 원효로2가',
 '마들로 녹천교서단',
 '통일로 서울혁신파크교차로',
 '동작대로 동작대교북단',
 '사평대로 교보타워사거리',
 '남부순환로 외발산사거리',
 '덕릉로 중계역',
 '원효로 e-테크벨리오피스텔',
 '올림픽로 올림픽파크텔앞',
 '강남순환로 관악터널입구부',
 '도봉로 도봉역',
 '중대로 가락시장역',
 '서오릉로 구산역',
 '목동동로 목동주차장',
 '도산대로 청담사거리',
 '개포로 개포고교',
 '양재대로55길 대청초교',
 '긴고랑로 용마사거리',
 '강남순환로 봉천터널중간부',
 '이촌로46길 한강시민공원이촌지구',
 '이문로 석관동새마을금고',
 '의사당대로 여의도공원앞',
 '강변역로 강변역',
 '충민로 글샘공원',
 '녹사평대로58길 서울용암초등학교',
 '삼성로 청담공원앞',
 '돌곶이로 북서울꿈의숲',
 '인촌로 고대앞사거리',
 '면목로 면곡시장',
 '섬밭로 중계그린아파트',
 '봉은사로 코엑스',
 '선유로 선유중고교',
 '올림픽대로 월드컵대교남단',
 '일원로 대청역',
 '한글비석로 을지병원',
 '올림픽로35길 잠실대교남단교차로',
 '영동대로 경기고교앞',
 '새문안로3길 경복궁역',
 '영동대로 삼성역',
 '사직로 경복궁역',
 '노원로 당현2교',
 '상암로 대명초교입구',
 '노량진로 대방역',
 '목동로 목동역',
 '당산로 영등포유통상가',
 '광평로 광평교',
 '테헤란로 강남역',
 '다산로 청구역',
 '올림픽대로 양화대교남단',
 '망우로 삼육서울병원앞',
 '동부간선도로 노원성당',
 '백련산로 은평구청입구',
 '마조로 마장역',
 '신월로 강월초교',
 '뚝섬로 서울숲푸르지오아파트',
 '월드컵북로 상암사거리',
 '마곡서로 외발산동',
 '퇴계로 퇴계로5가',
 '고산자로 제기사거리',
 '논현로 포이사거리',
 '신내로 신내지하차도',
 '백범로90길 삼각지고가차도(서측)',
 '가로공원로 강서나누리병원',
 '서초대로 진흥아파트',
 '양천로 개화사거리',
 '진황도로 신성아파트',
 '삼학사로 서울놀이마당앞',
 '선릉로 압구정로데오역',
 '월드컵북로 중암교',
 '안양천로 목동현대아파트',
 '여의동로 윤중초교앞',
 '효령로 뱅뱅사거리',
 '송월길 정동사거리',
 '수색로 시계(수색로)',
 '답십리로 전농1동',
 '삼일대로 퇴계로2가',
 '연서로 불광지구대',
 '상도로 보라매역',
 '봉우재로 중랑초교',
 '보문로 경동고교입구',
 '오류로 천왕역',
 '올림픽대로 반포주공아파트(올림픽대로)',
 '위례순환로 위례별초교',
 '우면산로 시계(우면산로)',
 '정릉천동로 제기동역',
 '창의문로 로마교황청대사관',
 '다산로 청계7가',
 '무학로 양지사거리',
 '성안로 강동성심병원교차로',
 '여의나루로 한국거래소',
 '벌말로 벌말로김포시계',
 '충민로2길 장지교',
 '아리수로 샘터근린공원',
 '와우산로 홍익대앞',
 '홍제천로 홍남교남측',
 '노원로 상계교',
 '삼양로 우이초등학교',
 '녹사평대로 녹사평역',
 '아차산로 구의현대아파트',
 '오목로 양강중교앞',
 '한강대로 삼각지역',
 '아리수로 고덕근린공원',
 '서빙고로 보광동사거리',
 '가마산로 구로IC',
 '안양천로 염창IC',
 '버드나루로 당산중교',
 '국제금융로 여의도한양아파트앞',
 '은평터널로 은평터널(남측)',
 '올림픽대로 잠실대교남단',
 '목동동로 현대백화점목동점',
 '왕십리로 뚝도아리정수센터',
 '동호로 청계5가',
 '위례성대로 오륜사거리',
 '오목로 과학수사연구소입구',
 '디지털로 구로남초교입구',
 '도림로 도신초교앞',
 '신풍로 보라매역',
 '관악로 서울대입구',
 '구천면로 명일역',
 '목동동로 목동근린공원',
 '쑥고개로 관악구청',
 '새문안로 서대문역',
 '여의대로 여의도공원앞',
 '종로 종로3가',
 '여의동로 윤중중교앞',
 '성안로 올림픽공원북2문',
 '소파로 퇴계로2가',
 '광나루로 성동교남단',
 '학동로 학동역',
 '동일로 성수사거리',
 '목동서로 열병합발전소',
 '신림로 서울대입구',
 '명일로 대명초교입구',
 '노해로 대한병원',
 '삼일대로 낙원상가',
 '문성로 신림초교',
 '호암로 미림여고입구',
 '서초중앙로 서초구립반포도서관',
 '화랑로 석계고가차도(동측)',
 '용마산로 망우사거리',
 '도림로 근로자회관',
 '성수이로 뚝도시장',
 '태봉로 KT연구개발본부',
 '시루봉로 신도봉사거리',
 '과천대로 사당역',
 '덕릉로 당고개길남양주시계',
 '강변역로 동서울터미널 동측',
 '창전로 창전사거리',
 '가락로 방이초교',
 '신목로 신정교서단',
 '월드컵로 디지털미디어시티입구',
 '동일로 영동대교북단',
 '삼성로 영동5교',
 '선유서로 양평역',
 '동남로82길 광문고교',
 '동일로 한국전력동부지점',
 '동교로 서교가든',
 '가마산로 대림3동사거리',
 '천호대로 상일초교',
 '오금로 개롱역',
 '도봉로 미아역',
 '역삼로 우성아파트',
 '월드컵로 마포구청',
 '올림픽로 송파구청',
 '농수산시장로 평화의공원입구삼거리',
 '통일로 불광역',
 '능동로 용마사거리',
 '전농로 답십리1동',
 '김포대로 방화2동상사마을입구',
 '장충단로 광희동사거리',
 '마천로 방이역',
 '남부순환로 예술의전당',
 '청계천로 청계8가',
 '송파대로 송파사거리',
 '일원로 영희초교',
 '가마산로 사러가시장앞',
 '강남대로 영동1교남단',
 '구천면로 천호시장',
 '서부간선도로 오목교동측',
 '압구정로 한남IC동측',
 '다산로 신당역',
 '송이로 문정중학교',
 '북악산로 사직단',
 '노량진로 노량진삼거리',
 '백련산로 은평병원',
 '사직로 정부서울청사',
 '사가정로 신답육교',
 '역삼로 역삼초교',
 '동일로 중원초교앞',
 '목동로 남부법원검찰청',
 '황물로 답십리5지구대',
 '벚꽃로 구로온누리아파트',
 '잠원로 한남IC서측(설악아파트)',
 '양평로 당산역',
 '남부순환로 서서울호수공원앞',
 '노해로 광산사거리',
 '망우로 중랑교동측',
 '목동남로 봉영여중목동고',
 '목동서로 목동1.2단지',
 '신내로 봉화환승주차장',
 '한천로 국립4.19묘지입구',
 '양재대로 수서IC',
 '올림픽로92길 브라운스톤암사',
 '양재대로55길 일원1동주민센터앞',
 '목동중앙본로 워베스빌앞',
 '금호로 금호사거리',
 '상암로 대명초교',
 '신정로 신트리공원앞',
 '양천로57길 가양3단지',
 '월드컵로 월드컵파크3단지',
 '자양번영로 신자초교입구',
 '소파로 백범광장',
 '한천로66길 석관중학교후문',
 '성산로 성산대교남단',
 '목동서로 목동2.3단지',
 '신이문로 신이문역',
 '송파대로 장지교',
 '천중로 길동생태공원',
 '수명로 강서면허시험장삼거리',
 '독서당로 한남오거리',
 '가마산로 가마산지하차도(남측)',
 '동일로243길 노원교(서단)',
 '여의대방로 여의교',
 '청파로 숙대입구',
 '흑석로 이화약국',
 '녹사평대로58길 남산2호터널북단',
 '인촌로8길 안암2교',
 '사직로8길 역사박물관',
 '돌곶이로 돌곶이역',
 '보광로 보광동사거리',
 '오금로 오금사거리',
 '도당로13길 방학동새마을금고',
 '헌릉로 세곡동사거리',
 '제기로 떡전교사거리',
 '한천로 광운초교앞',
 '동교로 망원정사거리',
 '월드컵로 월드컵경기장사거리',
 '도림천로 도림교',
 '디지털로10길 구로온누리아파트',
 '와우산로 극동방송국',
 '을지로 한양공고앞',
 '녹사평대로 크라운호텔',
 '강변역로4길 동서울호텔',
 '언주로 영동세브란스',
 '인수봉로 한신대',
 '통일로 서대문역',
 '시흥대로 시흥IC',
 '뚝섬로 신양초교',
 '목동동로 목동5단지상가',
 '삼청로 성북동서울아파트',
 '강남대로 한남대교북단',
 '안암로 안암오거리',
 '용마산로 용곡삼거리',
 '강변북로 가양대교북단',
 '명일로 명일여고앞',
 '을지로 을지로3가역',
 '공원로 스카이뷰아파트',
 '통일로 구파발역입구',
 '장터길 금호역',
 '동일로 묵동극동늘푸른아파트',
 '신반포로 논현역',
 '한가람로 CITY극동아파트103동앞',
 '공릉로 서울과학기술대',
 '신촌로 아현교차로',
 '모래내로 중동초교앞',
 '백제고분로 배명사거리',
 '역삼로 구역삼세무서',
 '청계천로 신답초교',
 '도봉로 방학역',
 '반포대로 서초3동사거리',
 '동일로 장안중학교',
 '세검정로 문화촌현대아파트',
 '여의공원로 한국방송공사앞',
 '동남로81길 묘곡초교',
 '세종대로21길 새문안교회',
 '선릉로 개포고교',
 '노해로 정의여중입구',
 '방화동로 김포공항입구',
 '망원로 망원우체국',
 '삼각산로 광산사거리',
 '노들로 성산대교남단교차로',
 '삼양로 청한빌라앞',
 '명일로 한산초교',
 '삼전로 탄천1교동측',
 '섬밭로 공릉라이프아파트',
 '영동대로 영동대교북단',
 '광나루로 어린이대공원역',
 '망우로 망우리고개(서울-구리시계)',
 '남대문로 숭례문',
 '남부순환로 신월IC',
 '테헤란로 삼성역',
 '독산로 독산3동주민센터',
 '영등포로 오목교동측',
 '명달로 서초고교',
 '강변북로 원효로진출입(강변북로)',
 '고덕로 동부기술교육원',
 '율곡로 원남동사거리',
 '서빙고로 한남역',
 '강변북로 영동대교북단',
 '동일로 도봉운전면허시험장',
 '시루봉로 숭미초교',
 '호암로 시흥벽산아파트',
 '광운로 광운대입구',
 '장한로 장안동삼거리',
 '과천대로 과천대로과천시계',
 '언주로 구룡초교',
 '전농로 전농동사거리',
 '구의강변로 구남초교',
 '새문안로5길 정부서울청사',
 '금낭화로 방화2동',
 '월계로 월계1교서측',
 '도신로 신도림고가차도앞',
 '창의문로 부암동주민센터',
 '신길로 대림삼거리',
 '화곡로 강서구청입구',
 '문정로 거여동사거리',
 '동부간선도로 초안산지하차도',
 '백석동길 북악산로입구',
 '동일로214길 상계백병원',
 '선유로 양화대교남단교차로',
 '세종대로18길 시청역',
 '청와대로 효자삼거리',
 '의사당대로 여의도공원교차로',
 '동부간선도로 창동교',
 '중계로 공릉터널',
 '역말로 동명여고',
 '한천로 휘경여중고',
 '효령로 효령아파트',
 '청파로 용산등기소',
 '장한로 장한평역',
 '삼성로 은마아파트입구',
 '신내로 봉화산역',
 '신월로 신정네거리역',
 '녹사평대로 반포대교북단',
 '가마산로 거리공원오거리',
 '가양대로 가양대교북단',
 '삼봉로 조계사앞',
 '상암로 상일초교',
 '신사로 구로디지털단지역',
 '상도로 장승배기',
 '고산자로 홍파초교',
 '강동대로 풍납종합사회복지관',
 '내부순환로 홍은램프진입(내부순환로)',
 '신반포로 이수교차로',
 '양재대로 방이역',
 '원효로 남영역',
 '외대역동로 외대앞역앞교차로',
 '성암로 중동교',
 '하늘길 김포공항입구',
 '중앙로 목동10단지',
 '자유로 강변북로고양시계',
 '동호로 종로5가',
 '천중로 신명초교입구',
 '아차산로 광진우체국',
 '모래내로 홍연2교서측',
 '만리재로 공덕오거리',
 '양재대로 양재IC동측',
 '양화로 양화대교북단',
 '구천면로 천일초교',
 '목동서로 양천우체국',
 '오리로 천왕역',
 '양재대로 동부기술교육원',
 '버드나루로 남부교육청앞',
 '상계로 상계초교입구',
 '장충단로 동대문역사문화공원역',
 '성북로 성북동서울아파트',
 '수표로 중부경찰서앞',
 '성산로 연희교차로',
 '송파대로 복정역',
 '압구정로 성수대교남단교차로',
 '광나루로56길 강변역',
 '올림픽대로 한강공원광나루지구',
 '북악산로 성북구민회관입구',
 '동부간선도로 동부간선도로-월계로램프(1)',
 '경춘북로 신내IC',
 '무학로 용두동사거리',
 '위례순환로 송례초교',
 '구로중앙로 NC백화점',
 '테헤란로115길 강남면허시험장',
 '서강로 광흥창역',
 '정릉로 정릉3동주민센터앞',
 '중랑천로 묵동교',
 '월드컵로 구룡삼거리',
 '금호로 청구역',
 '난곡로 신사동주민센터입구',
 '소공로 덕수궁',
 '백범로 공덕오거리',
 '시루봉로 선덕고교입구',
 '양재대로 길동사거리',
 '양재대로 탄천교',
 '강남순환로 선암영업소',
 '여의동로 마포대교남단',
 '공릉로 연촌초교',
 '안양천로 금천육교',
 '도림천로 신도림고가차도(북측)',
 '목동동로 목5동주민센터',
 '논현로 구역삼세무서',
 '방화대로 강서공고앞',
 '장승배기로 노량진삼거리',
 '올림픽대로 행주대교남단(개화IC)',
 '위례성대로 올림픽공원',
 '공릉로 을지병원',
 '밤고개로 밤고개로성남시계',
 '인촌로 안암역',
 '목동동로 양천세무서앞',
 '퇴계로 광희동사거리',
 '장한로 장안동사거리',
 '방화대로 신방화역',
 '송파대로 잠실대교남단교차로',
 '사평대로 삼호가든사거리',
 '테헤란로115길 봉은교',
 '내부순환로 성산분기점(내부순환로)',
 '아차산로 자양초교',
 '국제금융로 여의도환승센터',
 '오목로 오목교역',
 '가좌로 연희지하차도',
 '소공로 서울프라자호텔',
 '목동로 갈산초교삼거리',
 '은평터널로 은평터널삼거리',
 '화곡로 화곡로부천시계',
 '공항대로 양화교',
 '고덕로80길 상일동역(고덕우체국)',
 '위례성대로 방이초교',
 '동부간선도로 노원교',
 '여의대방로 원효대교남단',
 '이촌로 한강대교북단교차로',
 '가산디지털1로 구로한국후지필름',
 '서운로 무지개아파트',
 '선릉로 한티역',
 '돌곶이로 석관동새마을금고',
 '송이로32길 문덕초교',
 '북한산로 북한산성입구',
 '홍제천로 사천교동측',
 '신내로 화랑대역',
 '연남로 모래내지하차도',
 '서강로 서강대교북단',
 '자양로 구의사거리',
 '새창로 도화현대아파트',
 '성산로 연세대',
 '사직로 독립문역',
 '조원중앙로 신림현대아파트',
 '통일로 경찰청앞',
 '서초중앙로 법원검찰청',
 '도영로 대우드림빌앞',
 '덕릉로 노해근린공원',
 '양재대로 일원터널',
 '안양천로 금천교교차로',
 '동산로 국악고교앞',
 '강동대로 올림픽대교남단교차로',
 '분당수서로 청담대교북단',
 '동일로 노원구민회관',
 '경인로 영등포로타리',
 '논현로 학동역',
 '외대역동로 휘경2동주민센터',
 '중대로 오금공원',
 '아리수로 암사정수센터',
 '아리수로 강일5.7단지',
 '도당로13길 신한은행방학지점',
 '동부간선도로 노원구청(동부간선도로)',
 '상일로 고덕천.능곡교교차로',
 '남부순환로 수서IC',
 '경인고속도로 목동주경기장',
 '신반포로 반포역',
 '이문로 회기역앞',
 '목동동로 이대목동병원',
 '사직로8길 정부중앙청사별관',
 '북아현로 동양하이빌',
 '동일로173가길 공릉신명아파트',
 '목동중앙본로 염창역',
 '양재대로 올림픽공원',
 '강남대로 교육개발원입구',
 '구로중앙로 이화우성아파트',
 '마포대로 공덕오거리',
 '충정로 충정로역',
 '테헤란로114길 강남면허시험장',
 '노들로 여의교남단',
 '동호로 퇴계로5가',
 '양천로 가양3-5단지',
 '살곶이길 사근삼거리',
 '용마산로 능산삼거리',
 '여의서로 한국방송공사앞',
 '봉화산로 중랑구청사거리',
 '한천로 이문고가차도(북측)',
 '강서로29길 강서나누리병원',
 '이문로 외국어대',
 '북악산로 미아리고개예술극장',
 '풍성로 보훈병원',
 '화랑로 장위사거리',
 '밤고개로 수서역',
 '아차산로 올림픽대교북단교차로',
 '중계로 은행사거리',
 '거북골로 남가좌동새마을금고',
 '상봉로 동원사거리',
 '청파로47길 효창공원',
 '대학로 종로5가',
 '효창원로 원효동산호아파트',
 '장문로 크라운호텔',
 '세검정로 홍은사거리',
 '노해로 창4동주민센터',
 '신목로 목동청학스포츠타운',
 '경부고속도로 달래네고개',
 '신월여의지하도로 올림픽대로시점',
 '양화로 서교동사거리',
 '양재대로156길 배재중학교',
 '종로 종로구청입구',
 '신림로 신림교',
 '동소문로20길 성북경찰서',
 '남부순환로 남부순환로서초IC동측',
 '성균관로 국민생활관',
 '서울시립대로 르네스병원',
 '왕십리로 상왕십리역',
 '방화대로48길 강서공고앞',
 '초원로 방화초교',
 '광나루로 화양삼거리',
 '범안로 금천고가차도',
 '난곡로 난곡우체국앞',
 '공원로 태진운수',
 '신정중앙로 양동초교입구',
 '가재울미래로 남가좌동새마을금고',
 '석촌호수로 잠실주공1단지',
 '솔샘로 삼양입구사거리',
 '경부고속도로 반포IC북측경부고속진입',
 '황물로 삼희아파트',
 '서운로 서초구청',
 '새말로 건영아파트교차로',
 '면목로 중곡1동사거리',
 '남부순환로 개봉1동사거리',
 '광운로 광운대역',
 '봉은사로 종합운동장후문',
 '삼각산로 국립재활원앞',
 '국회대로 경인고속입구',
 '송파대로 건영아파트앞',
 '증가로 남가좌동사거리',
 '다산로 버티고개삼거리',
 '섬밭로 하계5.6단지',
 '한천로 배봉초교',
 '목동동로 목동5단지',
 '덕릉로 도봉문화정보센터',
 '충민로 가든파이브툴동',
 '한글비석로 노원자동차검사소',
 '동일로214길 당현2교',
 '송파대로 잠실역',
 '용마산로 중랑공영차고지',
 '신풍로 신풍역',
 '성중길 증산교',
 '우이천로 우이제3교(북단)',
 '녹사평대로26길 보광청화아파트',
 '올림픽대로 한남대교남단',
 '개화동로 방화2동상사마을입구',
 '현충로 흑석역',
 '소월로 남산도서관',
 '보광로 보광청화아파트',
 '약령시로 삼일교',
 '금낭화로 방화역',
 '내부순환로 정릉램프(내부순환로본선)',
 '새창로 용산전자상가',
 '봉은사로114길 강남경찰서',
 '고산자로 응봉삼거리',
 '화랑로 화랑대사거리',
 '면목로 상봉시장앞',
 '개화동로 행주대교남단교차로',
 '한글비석로 동일초교(동부간선도로)',
 '시루봉로 방학중학교',
 '노해로 창동교',
 '강남대로 우성아파트',
 '상일로 고덕주공3단지',
 '영중로 신세계백화점영등포점',
 '목동서로 양천문화회관공영주차장',
 '돈화문로 봉익동',
 '봉화산로 중화역입구대원사약국',
 '도영로 도림고가밑',
 '남부순환로 오류IC',
 '서강로 창전삼거리',
 '퇴계로 한양공고앞',
 '장안벚꽃로 장평교서측',
 '돈화문로 창덕궁',
 '백범로 용마루고개',
 '올림픽로98길 브라운스톤암사',
 '논현로 영동2교북단',
 '도봉로 대한병원',
 '목동동로 양천경찰서',
 '상계로 상계중앙시장',
 '강서로 우장산공원입구',
 '성안로 농협입구',
 '삼각산로 국립재활원',
 '후암로 용산고교',
 '증산로 난지IC(강변북로)',
 '시흥대로 박미삼거리',
 '진황도로 보훈병원입구',
 '사가정로 장안지하차도',
 '영동대로 대모산입구역',
 '선유로 문래동신안인스빌',
 '삼일대로 을지로2가',
 '테헤란로 역삼역',
 '도림로 대림역',
 '가산디지털2로 마이크로오피스앞',
 '동일로 먹골역',
 '삼학사로1길 탄천1교동측',
 '강남순환로 서초터널중간부',
 '오류로 시티월드앞',
 '성북로 성북초교앞',
 '월드컵북로 홍대입구역',
 '한글비석로 양지근린공원',
 '남부순환로 낙성대입구',
 '경부고속도로 잠원IC북측',
 '양재대로 구룡터널',
 '올림픽대로 가양대교남단',
 '공항대로59길 등촌역',
 '목동로 오금교서측',
 '서부간선도로 신정교동단',
 '경인로 시티월드앞',
 '서운로 진흥아파트',
 '안양천로 시흥대교교차로',
 '선릉로 선정릉역',
 '목동중앙로 목동3-4단지',
 '새창로 용문시장',
 '내부순환로 길음램프(내부순환로)',
 '헌릉로 복정역',
 '문정로 문정역',
 '회기로 회기역앞',
 '시흥대로 석수역',
 '시흥대로 대림삼거리',
 '창전로 구수동사거리',
 '월드컵북로 경성고교입구',
 '신월로 서울남부지방법원',
 '삼성로 포스코사거리',
 '동일로 중화역',
 '인촌로 안암동주민센터',
 '수락산로 상원초교',
 '동호로 옥수터널',
 '공원로 새솔금호아파트',
 '연서로 구산역',
 '마곡중앙5로 신방화역',
 '서부간선지하도로 성산대교남단',
 '조원중앙로 구로전화국',
 '목동동로 목5동성당',
 '구로동로 유엔미아파트',
 '공원로 구로거리공원동',
 '올림픽로43길 올림픽대교남단교차로',
 '사직로 경복궁교차로',
 '부일로 오류고가차도',
 '봉천로 롯데백화점관악점',
 '뚝섬로 동서울호텔',
 '공릉로 용동초교',
 '경인로 동양미래대학',
 '마천로 마천로성남시계',
 '목동중앙로 목동극동아파트',
 '신월여의지하도로 목동교서단',
 '창경궁로 성균관대입구',
 '두텁바위로 용산고교',
 '덕수궁길 새문안교회',
 '노원로 화랑대사거리',
 '안양천로 철산리버빌주공아파트',
 '대방천로 신길광장공원앞',
 '통일로 통일로고양시계',
 '반포대로 서울성모병원',
 '갈현로 시립서북병원',
 '당산로 당산역(노들로)',
 '양재대로 둔촌사거리',
 '세종대로 숭례문',
 '강변북로 동작대교북단',
 '중앙로 고척동우체국',
 '공항대로 발산역',
 '고척로 고척2파출소앞',
 '구로중앙로 구로초교',
 '목동서로 한국전력강서지점',
 '양재천로 영동5교',
 '상계로 노원구청(동부간선도로)',
 '양산로(송파) 거여역',
 '신촌로 동교동삼거리',
 '분당수서로 복정교차로',
 '가산디지털2로 디지털3단지',
 '마곡중앙5로 마곡나루역',
 '한가람로 풍납갑을아파트',
 '화랑로 월곡역',
 '국제금융로 한국거래소',
 '도봉로 우이교',
 '용마산로 중곡3동우편취급국',
 '당산로54길 삼환아파트',
 '시흥대로 시흥사거리',
 '마포대로 마포우체국',
 '사당로 이수역',
 '여의공원로 여의도공원서',
 '문정로 문덕초교',
 '광나루로 광장자이아파트',
 '도봉로 정의여중입구',
 '국회대로 목동교서단',
 '독막로 광흥창역',
 '제기로 고대앞사거리',
 '왕십리로 서울숲입구',
 '디지털로 디지털단지오거리',
 '삼각산로 우이초등교앞',
 '공항대로 송정역',
 '신촌로 충정로역',
 '군자로 화양삼거리',
 '언주로 도산공원',
 '양평로 선유도역',
 '안양천로 광명고가차도(북측)',
 '가좌로 홍연2교동측',
 '다산로 약수역',
 '불광로 불광중학교',
 '안암로 대광중고교',
 '시흥대로 디지털단지입구',
 '곰달래로 목동사거리',
 '마장로 동대문디자인플라자',
 '창경궁로 퇴계로4가',
 '서초대로 서초고교',
 '모래내로 연가교(서측)',
 '이촌로46길 이촌로강변북로진입',
 '대흥로 대흥역',
 '당산로54길 당산중교',
 '디지털로 2공단사거리',
 '강변북로 양화대교북단',
 '목동동로 목동현대하이페리온',
 '섬밭로 월릉교동측',
 '월드컵북로 상암초교',
 '자하문로 베네스트아파트',
 '문래로 신세계백화점영등포점',
 '오금로 거여역',
 '성산로 봉원고가차도',
 '수색로 사천교동측',
 '영등포로 영등포시장',
 '중랑역로 먹골역입구',
 '천호대로 상일동동아아파트입구',
 '아리수로 고덕시영아파트',
 '한가람로 종합운동장JC',
 '양녕로 현대시장입구',
 '북촌로 삼청공원입구',
 '테헤란로 선릉역',
 '청파로 서울역(서부)',
 '한강대로 전자상가입구',
 '장안벚꽃로 군자교서단',
 '가산디지털1로 금천고가차도',
 '도림천로 대림역',
 ...]

# nan 도 지워버리자고

In [141]:
import numpy as np

In [168]:
speed_location_pd = pd.DataFrame(speed_location_list_final)
speed_location_pd = speed_location_pd.dropna()
speed_location_pd

                   0
0        남부순환로 난곡사거리
2          한강대로 용산역앞
3         가양대로 구룡삼거리
4           삼일대로 안국역
5         삼전로 잠실3삼거리
...              ...
3130         동일로 면목교
3131   개봉로 경서농협개봉역지점
3132       양천로 방화2단지
3133  통일로 은평여성인력개발센터
3134     강변북로 서강대교북단

[3134 rows x 1 columns]

In [169]:
speed_location_pd =speed_location_pd.reset_index()
speed_location_pd = speed_location_pd.drop(['index'], axis=1 )
speed_location_pd

                   0
0        남부순환로 난곡사거리
1          한강대로 용산역앞
2         가양대로 구룡삼거리
3           삼일대로 안국역
4         삼전로 잠실3삼거리
...              ...
3129         동일로 면목교
3130   개봉로 경서농협개봉역지점
3131       양천로 방화2단지
3132  통일로 은평여성인력개발센터
3133     강변북로 서강대교북단

[3134 rows x 1 columns]

In [170]:
df2 = pd.DataFrame(speed_location_pd[0].str.split(' ').tolist(),columns=['도로', '위치', '야', '호'])
df2

         도로          위치     야     호
0     남부순환로       난곡사거리  None  None
1      한강대로        용산역앞  None  None
2      가양대로       구룡삼거리  None  None
3      삼일대로         안국역  None  None
4       삼전로      잠실3삼거리  None  None
...     ...         ...   ...   ...
3129    동일로         면목교  None  None
3130    개봉로   경서농협개봉역지점  None  None
3131    양천로       방화2단지  None  None
3132    통일로  은평여성인력개발센터  None  None
3133   강변북로      서강대교북단  None  None

[3134 rows x 4 columns]

In [171]:
speed_location_pd["위치"] = df2["위치"]
speed_location_pd

                   0          위치
0        남부순환로 난곡사거리       난곡사거리
1          한강대로 용산역앞        용산역앞
2         가양대로 구룡삼거리       구룡삼거리
3           삼일대로 안국역         안국역
4         삼전로 잠실3삼거리      잠실3삼거리
...              ...         ...
3129         동일로 면목교         면목교
3130   개봉로 경서농협개봉역지점   경서농협개봉역지점
3131       양천로 방화2단지       방화2단지
3132  통일로 은평여성인력개발센터  은평여성인력개발센터
3133     강변북로 서강대교북단      서강대교북단

[3134 rows x 2 columns]

In [172]:
speed_location_pd.to_csv('./speed_location.csv', encoding = 'EUC-KR', index=False)

# 위의 친구가 구글 API로 들어갈 것이다.

In [148]:
pip install googlemaps

Requirement already satisfied: googlemaps in c:\python\envs\opencv\lib\site-packages (4.7.0)
Requirement already satisfied: requests<3.0,>=2.20.0 in c:\python\envs\opencv\lib\site-packages (from googlemaps) (2.28.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\python\envs\opencv\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2022.9.24)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python\envs\opencv\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (1.26.11)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\python\envs\opencv\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in c:\python\envs\opencv\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.3)
Note: you may need to restart the kernel to use updated packages.

In [149]:
from googlemaps import Client as GoogleMaps

In [150]:
gmaps = GoogleMaps('key')

 API queries_quota: 60

In [174]:
speed_location_pd = pd.read_csv('./speed_location.csv', encoding="EUC-KR")

In [175]:
speed_location_pd['long'] = ""
speed_location_pd['lat'] = ""

In [176]:
speed_location_pd

                   0          위치 long lat
0        남부순환로 난곡사거리       난곡사거리
1          한강대로 용산역앞        용산역앞
2         가양대로 구룡삼거리       구룡삼거리
3           삼일대로 안국역         안국역
4         삼전로 잠실3삼거리      잠실3삼거리
...              ...         ...  ...  ..
3129         동일로 면목교         면목교
3130   개봉로 경서농협개봉역지점   경서농협개봉역지점
3131       양천로 방화2단지       방화2단지
3132  통일로 은평여성인력개발센터  은평여성인력개발센터
3133     강변북로 서강대교북단      서강대교북단

[3134 rows x 4 columns]

In [154]:
pip install tqdm

Requirement already satisfied: tqdm in c:\python\envs\opencv\lib\site-packages (4.64.1)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: colorama in c:\python\envs\opencv\lib\site-packages (from tqdm) (0.4.5)

In [177]:
import time
from tqdm import tqdm

# 돈 없으니까 결과 나오면 꼭 캡쳐해줘.... 제발 다시돌리기 싫어

In [178]:
fail_list = []
fail_location_list = []

for x in tqdm(range(len(speed_location_pd))):
    try:
        time.sleep(1) #to add delay in case of large DFs
        geocode_result = gmaps.geocode(speed_location_pd["위치"][x])
        speed_location_pd['lat'][x] = geocode_result[0]['geometry']['location'] ['lat']
        speed_location_pd['long'][x] = geocode_result[0]['geometry']['location']['lng']
    except IndexError:
        try:
            time.sleep(1) #to add delay in case of large DFs
            geocode_result = gmaps.geocode(speed_location_pd[0][x])
            speed_location_pd['lat'][x] = geocode_result[0]['geometry']['location'] ['lat']
            speed_location_pd['long'][x] = geocode_result[0]['geometry']['location']['lng']
        except:
            fail_list.append(x)
            fail_location_list.append(speed_location_pd["위치"][x])
    except Exception as e:
        print(x, "- Unexpected error occurred.", e )
speed_location_pd

100%|████████████████████████████████████████████████████████████████████████████| 3134/3134 [1:08:21<00:00,  1.31s/it]

                   0          위치        long        lat
0        남부순환로 난곡사거리       난곡사거리  126.914506  37.481794
1          한강대로 용산역앞        용산역앞  126.965222  37.526289
2         가양대로 구룡삼거리       구룡삼거리  126.876229   37.58017
3           삼일대로 안국역         안국역  126.985472  37.576556
4         삼전로 잠실3삼거리      잠실3삼거리
...              ...         ...         ...        ...
3129         동일로 면목교         면목교  127.096569  37.584118
3130   개봉로 경서농협개봉역지점   경서농협개봉역지점
3131       양천로 방화2단지       방화2단지  126.818992  37.574644
3132  통일로 은평여성인력개발센터  은평여성인력개발센터
3133     강변북로 서강대교북단      서강대교북단  126.925044  37.537018

[3134 rows x 4 columns]

In [179]:
speed_location_pd.to_csv('./speed_location_final.csv', encoding="EUC-KR", index=False)

In [183]:
len(fail_list)

585

In [184]:
len(fail_location_list)

585

In [187]:
fail_pd=pd.DataFrame(fail_list)

In [189]:
fail_pd["실패위치"] = pd.DataFrame(fail_location_list)

In [190]:
fail_pd

        0            실패위치
0       4          잠실3삼거리
1       9         영동2교교차로
2      10           의원회관앞
3      29     남부순환로탄천IC진입
4      31           종합운동장
..    ...             ...
580  3109        신도림고가차도앞
581  3119  탄천IC진입(동부간선도로)
582  3125      오목지하차도(동단)
583  3130       경서농협개봉역지점
584  3132      은평여성인력개발센터

[585 rows x 2 columns]

In [191]:
fail_pd.to_csv('./fail_pd.csv', encoding="EUC-KR", index=False)

In [192]:
speed_location_pd

                   0          위치        long        lat
0        남부순환로 난곡사거리       난곡사거리  126.914506  37.481794
1          한강대로 용산역앞        용산역앞  126.965222  37.526289
2         가양대로 구룡삼거리       구룡삼거리  126.876229   37.58017
3           삼일대로 안국역         안국역  126.985472  37.576556
4         삼전로 잠실3삼거리      잠실3삼거리
...              ...         ...         ...        ...
3129         동일로 면목교         면목교  127.096569  37.584118
3130   개봉로 경서농협개봉역지점   경서농협개봉역지점
3131       양천로 방화2단지       방화2단지  126.818992  37.574644
3132  통일로 은평여성인력개발센터  은평여성인력개발센터
3133     강변북로 서강대교북단      서강대교북단  126.925044  37.537018

[3134 rows x 4 columns]

In [193]:
merge_left = pd.merge(fail_pd, speed_location_pd , how='inner', left_on='실패위치', right_on='위치')
merge_left

         0            실패위치                     0              위치 long lat
0        4          잠실3삼거리            삼전로 잠실3삼거리          잠실3삼거리
1        4          잠실3삼거리            잠실로 잠실3삼거리          잠실3삼거리
2     3108          잠실3삼거리            삼전로 잠실3삼거리          잠실3삼거리
3     3108          잠실3삼거리            잠실로 잠실3삼거리          잠실3삼거리
4        9         영동2교교차로          바우뫼로 영동2교교차로         영동2교교차로
...    ...             ...                   ...             ...  ...  ..
1112  3097           청계6가앞             마장로 청계6가앞           청계6가앞
1113  3102          삼도오피스텔            은행로 삼도오피스텔          삼도오피스텔
1114  3119  탄천IC진입(동부간선도로)  분당수서로 탄천IC진입(동부간선도로)  탄천IC진입(동부간선도로)
1115  3130       경서농협개봉역지점         개봉로 경서농협개봉역지점       경서농협개봉역지점
1116  3132      은평여성인력개발센터        통일로 은평여성인력개발센터      은평여성인력개발센터

[1117 rows x 6 columns]

In [195]:
merge_left_drop = merge_left.drop_duplicates(0)
merge_left_drop

         0            실패위치                     0              위치 long lat
0        4          잠실3삼거리            삼전로 잠실3삼거리          잠실3삼거리
2     3108          잠실3삼거리            삼전로 잠실3삼거리          잠실3삼거리
4        9         영동2교교차로          바우뫼로 영동2교교차로         영동2교교차로
6     1426         영동2교교차로          바우뫼로 영동2교교차로         영동2교교차로
8       10           의원회관앞            여의서로 의원회관앞           의원회관앞
...    ...             ...                   ...             ...  ...  ..
1112  3097           청계6가앞             마장로 청계6가앞           청계6가앞
1113  3102          삼도오피스텔            은행로 삼도오피스텔          삼도오피스텔
1114  3119  탄천IC진입(동부간선도로)  분당수서로 탄천IC진입(동부간선도로)  탄천IC진입(동부간선도로)
1115  3130       경서농협개봉역지점         개봉로 경서농협개봉역지점       경서농협개봉역지점
1116  3132      은평여성인력개발센터        통일로 은평여성인력개발센터      은평여성인력개발센터

[585 rows x 6 columns]

In [196]:
merge_left_drop = merge_left_drop.drop(['위치', 'long', 'lat'], axis=1)
merge_left_drop

         0            실패위치                     0
0        4          잠실3삼거리            삼전로 잠실3삼거리
2     3108          잠실3삼거리            삼전로 잠실3삼거리
4        9         영동2교교차로          바우뫼로 영동2교교차로
6     1426         영동2교교차로          바우뫼로 영동2교교차로
8       10           의원회관앞            여의서로 의원회관앞
...    ...             ...                   ...
1112  3097           청계6가앞             마장로 청계6가앞
1113  3102          삼도오피스텔            은행로 삼도오피스텔
1114  3119  탄천IC진입(동부간선도로)  분당수서로 탄천IC진입(동부간선도로)
1115  3130       경서농협개봉역지점         개봉로 경서농협개봉역지점
1116  3132      은평여성인력개발센터        통일로 은평여성인력개발센터

[585 rows x 3 columns]

In [197]:
merge_left_drop.columns = ['틀린인덱스', '실패위치', '도로명 포함 실패위치']

In [214]:
merge_left_drop

      틀린인덱스            실패위치           도로명 포함 실패위치
0         4          잠실3삼거리            삼전로 잠실3삼거리
2      3108          잠실3삼거리            삼전로 잠실3삼거리
4         9         영동2교교차로          바우뫼로 영동2교교차로
6      1426         영동2교교차로          바우뫼로 영동2교교차로
8        10           의원회관앞            여의서로 의원회관앞
...     ...             ...                   ...
1112   3097           청계6가앞             마장로 청계6가앞
1113   3102          삼도오피스텔            은행로 삼도오피스텔
1114   3119  탄천IC진입(동부간선도로)  분당수서로 탄천IC진입(동부간선도로)
1115   3130       경서농협개봉역지점         개봉로 경서농협개봉역지점
1116   3132      은평여성인력개발센터        통일로 은평여성인력개발센터

[585 rows x 3 columns]

In [233]:
merge_left_drop.to_csv('./fail_pd.csv', encoding="EUC-KR", index=False)

In [245]:
fail_pd_se = pd.read_csv('./fail_pd.csv', encoding='EUC-KR')

In [246]:
fail_pd_se

     틀린인덱스            실패위치           도로명 포함 실패위치       도로명 포함 실패위치(수정)
0        4          잠실3삼거리            삼전로 잠실3삼거리             삼전로 잠실삼거리
1     3108          잠실3삼거리            삼전로 잠실3삼거리             삼전로 잠실삼거리
2        9         영동2교교차로          바우뫼로 영동2교교차로          바우뫼로 영동2교교차로
3     1426         영동2교교차로          바우뫼로 영동2교교차로          바우뫼로 영동2교교차로
4       10           의원회관앞            여의서로 의원회관앞          여의서로 국회의원회관앞
..     ...             ...                   ...                   ...
580   3097           청계6가앞             마장로 청계6가앞             마장로 청계6가앞
581   3102          삼도오피스텔            은행로 삼도오피스텔            은행로 삼도오피스텔
582   3119  탄천IC진입(동부간선도로)  분당수서로 탄천IC진입(동부간선도로)  분당수서로 탄천IC진입(동부간선도로)
583   3130       경서농협개봉역지점         개봉로 경서농협개봉역지점         개봉로 경서농협개봉역지점
584   3132      은평여성인력개발센터        통일로 은평여성인력개발센터        통일로 은평여성인력개발센터

[585 rows x 4 columns]

In [247]:
fail_pd_se ['long'] = ""
fail_pd_se ['lat'] = ""

In [248]:
fail_list = []
fail_location_list = []

for x in tqdm(range(len(fail_pd_se))):
    try:
        time.sleep(1) #to add delay in case of large DFs
        geocode_result = gmaps.geocode(fail_pd_se["도로명 포함 실패위치"][x])
        fail_pd_se['lat'][x] = geocode_result[0]['geometry']['location'] ['lat']
        fail_pd_se['long'][x] = geocode_result[0]['geometry']['location']['lng']
    except IndexError:
        try:
            time.sleep(1) #to add delay in case of large DFs
            geocode_result = gmaps.geocode(speed_location_pd["실패위치"][x])
            fail_pd_se['lat'][x] = geocode_result[0]['geometry']['location'] ['lat']
            fail_pd_se['long'][x] = geocode_result[0]['geometry']['location']['lng']
        except:
            fail_list.append(x)
            fail_location_list.append(speed_location_pd["위치"][x])
    except Exception as e:
        print(x, "- Unexpected error occurred.", e )
fail_pd_se

  0%|▎                                                                                 | 2/585 [00:04<20:44,  2.13s/it]C:\Users\김두엽\AppData\Local\Temp\ipykernel_35636\2587475214.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fail_pd_se['lat'][x] = geocode_result[0]['geometry']['location'] ['lat']
C:\Users\김두엽\AppData\Local\Temp\ipykernel_35636\2587475214.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fail_pd_se['long'][x] = geocode_result[0]['geometry']['location']['lng']
100%|████████████████████████████████████████████████████████████████████████████████| 585/585 [14:27<00:00,  1.48s/it]

,틀린인덱스,실패위치,도로명 포함 실패위치,도로명 포함 실패위치(수정),long,lat
0,4,잠실3삼거리,삼전로 잠실3삼거리,삼전로 잠실삼거리,,
1,3108,잠실3삼거리,삼전로 잠실3삼거리,삼전로 잠실삼거리,,
2,9,영동2교교차로,바우뫼로 영동2교교차로,바우뫼로 영동2교교차로,127.035941,37.476965
3,1426,영동2교교차로,바우뫼로 영동2교교차로,바우뫼로 영동2교교차로,127.035941,37.476965
4,10,의원회관앞,여의서로 의원회관앞,여의서로 국회의원회관앞,,
...,...,...,...,...,...,...
580,3097,청계6가앞,마장로 청계6가앞,마장로 청계6가앞,,
581,3102,삼도오피스텔,은행로 삼도오피스텔,은행로 삼도오피스텔,126.924839,37.52989
582,3119,탄천IC진입(동부간선도로),분당수서로 탄천IC진입(동부간선도로),분당수서로 탄천IC진입(동부간선도로),127.118906,37.382699
583,3130,경서농협개봉역지점,개봉로 경서농협개봉역지점,개봉로 경서농협개봉역지점,,
584,3132,은평여성인력개발센터,통일로 은평여성인력개발센터,통일로 은평여성인력개발센터,126.932244,37.607288

In [271]:
speed_location_pd_2 = speed_location_pd
speed_location_pd_2 = speed_location_pd_2.reset_index()
speed_location_pd_2.columns = ['index', '위치', '도로명 포함 위치', 'long', 'lat' ]
speed_location_pd_2

      index              위치   도로명 포함 위치        long        lat
0         0     남부순환로 난곡사거리       난곡사거리  126.914506  37.481794
1         1       한강대로 용산역앞        용산역앞  126.965222  37.526289
2         2      가양대로 구룡삼거리       구룡삼거리  126.876229   37.58017
3         3        삼일대로 안국역         안국역  126.985472  37.576556
4         4      삼전로 잠실3삼거리      잠실3삼거리
...     ...             ...         ...         ...        ...
3129   3129         동일로 면목교         면목교  127.096569  37.584118
3130   3130   개봉로 경서농협개봉역지점   경서농협개봉역지점
3131   3131       양천로 방화2단지       방화2단지  126.818992  37.574644
3132   3132  통일로 은평여성인력개발센터  은평여성인력개발센터
3133   3133     강변북로 서강대교북단      서강대교북단  126.925044  37.537018

[3134 rows x 5 columns]

In [272]:
speed_location_pd_2['long'].replace('',np.nan, inplace=True)
speed_location_pd_2

      index              위치   도로명 포함 위치        long        lat
0         0     남부순환로 난곡사거리       난곡사거리  126.914506  37.481794
1         1       한강대로 용산역앞        용산역앞  126.965222  37.526289
2         2      가양대로 구룡삼거리       구룡삼거리  126.876229   37.58017
3         3        삼일대로 안국역         안국역  126.985472  37.576556
4         4      삼전로 잠실3삼거리      잠실3삼거리         NaN
...     ...             ...         ...         ...        ...
3129   3129         동일로 면목교         면목교  127.096569  37.584118
3130   3130   개봉로 경서농협개봉역지점   경서농협개봉역지점         NaN
3131   3131       양천로 방화2단지       방화2단지  126.818992  37.574644
3132   3132  통일로 은평여성인력개발센터  은평여성인력개발센터         NaN
3133   3133     강변북로 서강대교북단      서강대교북단  126.925044  37.537018

[3134 rows x 5 columns]

In [273]:
speed_location_pd_2 = speed_location_pd_2.dropna()
speed_location_pd_2

      index           위치 도로명 포함 위치        long        lat
0         0  남부순환로 난곡사거리     난곡사거리  126.914506  37.481794
1         1    한강대로 용산역앞      용산역앞  126.965222  37.526289
2         2   가양대로 구룡삼거리     구룡삼거리  126.876229   37.58017
3         3     삼일대로 안국역       안국역  126.985472  37.576556
5         5   월계로 북서울꿈의숲    북서울꿈의숲  127.040625  37.621431
...     ...          ...       ...         ...        ...
3127   3127    남부순환로 대치역       대치역  127.063446  37.494569
3128   3128  성수일로 경동초교입구    경동초교입구  127.050463  37.542956
3129   3129      동일로 면목교       면목교  127.096569  37.584118
3131   3131    양천로 방화2단지     방화2단지  126.818992  37.574644
3133   3133  강변북로 서강대교북단    서강대교북단  126.925044  37.537018

[2549 rows x 5 columns]

In [262]:
fail_pd_se_2 =  fail_pd_se
fail_pd_se_2["index"] = fail_pd_se_2["틀린인덱스"] 
fail_pd_se_2 = fail_pd_se_2.drop(['도로명 포함 실패위치(수정)', '틀린인덱스'], axis=1)
fail_pd_se_2.columns = ['위치', '도로명 포함 위치', 'long', 'lat', 'index']
fail_pd_se_2 = fail_pd_se_2[['index',  '도로명 포함 위치', '위치',  'long', 'lat' ]]
fail_pd_se_2

     index             도로명 포함 위치              위치        long        lat
0        4            삼전로 잠실3삼거리          잠실3삼거리
1     3108            삼전로 잠실3삼거리          잠실3삼거리
2        9          바우뫼로 영동2교교차로         영동2교교차로  127.035941  37.476965
3     1426          바우뫼로 영동2교교차로         영동2교교차로  127.035941  37.476965
4       10            여의서로 의원회관앞           의원회관앞
..     ...                   ...             ...         ...        ...
580   3097             마장로 청계6가앞           청계6가앞
581   3102            은행로 삼도오피스텔          삼도오피스텔  126.924839   37.52989
582   3119  분당수서로 탄천IC진입(동부간선도로)  탄천IC진입(동부간선도로)  127.118906  37.382699
583   3130         개봉로 경서농협개봉역지점       경서농협개봉역지점
584   3132        통일로 은평여성인력개발센터      은평여성인력개발센터  126.932244  37.607288

[585 rows x 5 columns]

In [274]:
fail_pd_se_2['long'].replace('',np.nan, inplace=True)
fail_pd_se_2

     index             도로명 포함 위치              위치        long        lat
0        4            삼전로 잠실3삼거리          잠실3삼거리         NaN
1     3108            삼전로 잠실3삼거리          잠실3삼거리         NaN
2        9          바우뫼로 영동2교교차로         영동2교교차로  127.035941  37.476965
3     1426          바우뫼로 영동2교교차로         영동2교교차로  127.035941  37.476965
4       10            여의서로 의원회관앞           의원회관앞         NaN
..     ...                   ...             ...         ...        ...
580   3097             마장로 청계6가앞           청계6가앞         NaN
581   3102            은행로 삼도오피스텔          삼도오피스텔  126.924839   37.52989
582   3119  분당수서로 탄천IC진입(동부간선도로)  탄천IC진입(동부간선도로)  127.118906  37.382699
583   3130         개봉로 경서농협개봉역지점       경서농협개봉역지점         NaN
584   3132        통일로 은평여성인력개발센터      은평여성인력개발센터  126.932244  37.607288

[585 rows x 5 columns]

In [275]:
fail_pd_se_2 = fail_pd_se_2.dropna()
fail_pd_se_2

     index             도로명 포함 위치              위치        long        lat
2        9          바우뫼로 영동2교교차로         영동2교교차로  127.035941  37.476965
3     1426          바우뫼로 영동2교교차로         영동2교교차로  127.035941  37.476965
7       31           백제고분로 종합운동장           종합운동장  127.098125  37.507956
8     2745           백제고분로 종합운동장           종합운동장  127.098125  37.507956
9       36           디지털로 디지털3단지          디지털3단지  126.881415  37.475825
..     ...                   ...             ...         ...        ...
578   3081             도당로 성원아파트           성원아파트  127.035894  37.661506
579   3073              흑석로 이화빌라            이화빌라  126.957062  37.506554
581   3102            은행로 삼도오피스텔          삼도오피스텔  126.924839   37.52989
582   3119  분당수서로 탄천IC진입(동부간선도로)  탄천IC진입(동부간선도로)  127.118906  37.382699
584   3132        통일로 은평여성인력개발센터      은평여성인력개발센터  126.932244  37.607288

[372 rows x 5 columns]

In [276]:
iwant_sleep = pd.concat([fail_pd_se_2, speed_location_pd_2 ])
iwant_sleep

      index     도로명 포함 위치           위치        long        lat
2         9  바우뫼로 영동2교교차로      영동2교교차로  127.035941  37.476965
3      1426  바우뫼로 영동2교교차로      영동2교교차로  127.035941  37.476965
7        31   백제고분로 종합운동장        종합운동장  127.098125  37.507956
8      2745   백제고분로 종합운동장        종합운동장  127.098125  37.507956
9        36   디지털로 디지털3단지       디지털3단지  126.881415  37.475825
...     ...           ...          ...         ...        ...
3127   3127           대치역    남부순환로 대치역  127.063446  37.494569
3128   3128        경동초교입구  성수일로 경동초교입구  127.050463  37.542956
3129   3129           면목교      동일로 면목교  127.096569  37.584118
3131   3131         방화2단지    양천로 방화2단지  126.818992  37.574644
3133   3133        서강대교북단  강변북로 서강대교북단  126.925044  37.537018

[2921 rows x 5 columns]

In [278]:
iwant_sleep.to_csv('./speed_location_final.csv', encoding="EUC-KR", index=False)

In [279]:
len(fail_list)

213

In [281]:
fail_pd=pd.DataFrame(fail_list)
fail_pd["실패위치"] = pd.DataFrame(fail_location_list)
merge_left = pd.merge(fail_pd, speed_location_pd , how='inner', left_on='실패위치', right_on='위치')
merge_left_drop.columns = ['틀린인덱스', '실패위치', '도로명 포함 실패위치']
merge_left

       0    실패위치              0      위치        long        lat
0      0   난곡사거리    남부순환로 난곡사거리   난곡사거리  126.914506  37.481794
1      0   난곡사거리      난곡로 난곡사거리   난곡사거리  126.914506  37.481794
2      1    용산역앞      한강대로 용산역앞    용산역앞  126.965222  37.526289
3      1    용산역앞      서빙고로 용산역앞    용산역앞  126.965222  37.526289
4      4  잠실3삼거리     삼전로 잠실3삼거리  잠실3삼거리
..   ...     ...            ...     ...         ...        ...
418  580  거여동사거리     오금로 거여동사거리  거여동사거리  127.139372  37.495602
419  580  거여동사거리     문정로 거여동사거리  거여동사거리  127.139372  37.495602
420  583   상계백병원  동일로213길 상계백병원   상계백병원  127.063143  37.648508
421  583   상계백병원  동일로214길 상계백병원   상계백병원  127.063143  37.648508
422  583   상계백병원      동일로 상계백병원   상계백병원  127.063143  37.648508

[423 rows x 6 columns]

In [242]:
results = gmaps.geocode('통일로 은평여성인력개발센터')
results

[{'address_components': [{'long_name': '은평여성인력개발센터',
    'short_name': '은평여성인력개발센터',
    'types': ['establishment', 'point_of_interest', 'transit_station']},
   {'long_name': 'Seoul',
    'short_name': 'Seoul',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': 'South Korea',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '122-020',
    'short_name': '122-020',
    'types': ['postal_code']}],
  'formatted_address': 'South Korea, Seoul, 은평여성인력개발센터',
  'geometry': {'location': {'lat': 37.607288, 'lng': 126.932244},
   'location_type': 'GEOMETRIC_CENTER',
   'viewport': {'northeast': {'lat': 37.60863698029149,
     'lng': 126.9335929802915},
    'southwest': {'lat': 37.6059390197085, 'lng': 126.9308950197085}}},
  'partial_match': True,
  'place_id': 'ChIJh9BW5yGYfDURiilCdfRxH04',
  'plus_code': {'compound_code': 'JW4J+WV Seoul, South Korea',
   'global_code': '8Q98JW4J+WV'},
  'types': ['establishment', 'point_of_interest', 'transit_station']}]