In [2]:
import pandas as pd

In [37]:
bus_2019 = pd.read_csv('./2019_bus_commute.csv')
bus_2019 = bus_2019.drop('노선ID', axis=1)
bus_2019

,사용년월,역명,출근시간(04~09) 승차,출근시간(07~10) 하차,퇴근시간(16~20) 승차,퇴근시간(17~21) 하차,점심시간,저녁시간,늦은시간(20~00) 승차,늦은시간(21~02) 하차,총 승차 인원,총 하차 인원,연도
0,201901,석계역2번출구,0,0,0,0,0,0,0,17,58,31,2019
1,201901,한성여객종점,223,31,232,140,7,-315,72,16,683,223,2019
2,201901,노원평생학습관,85,0,148,4,-42,-118,54,0,404,18,2019
3,201901,서울시립북서울미술관,321,6,424,16,-132,-299,197,5,1391,71,2019
4,201901,중계역,823,6,293,56,-194,-278,108,18,1713,168,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...
465032,201912,책향기마을,5,88,0,629,165,-426,0,595,9,1418,2019
465033,201912,중앙공원,1,70,0,228,117,-108,1,219,3,619,2019
465034,201912,우리은행앞,3,223,17,961,389,-611,12,819,49,2313,2019
465035,201912,청석마을8단지,4,71,0,376,121,-220,4,344,10,824,2019
465036,201912,교하차고지,0,7,0,13,15,-6,0,18,0,63,2019

In [38]:
bus_2019 = bus_2019.astype({'사용년월' : 'string'})
bus_2019['월'] = bus_2019['사용년월'].str[4:]
bus_2019 = bus_2019.drop('사용년월', axis = 1 )
bus_2019 = bus_2019[['역명', '연도', '월', '총 승차 인원', '총 하차 인원', '출근시간(04~09) 승차', '출근시간(07~10) 하차',
                    '퇴근시간(16~20) 승차', '퇴근시간(17~21) 하차', '늦은시간(20~00) 승차', '늦은시간(21~02) 하차', '점심시간', '저녁시간']]
bus_2019

,역명,연도,월,총 승차 인원,총 하차 인원,출근시간(04~09) 승차,출근시간(07~10) 하차,퇴근시간(16~20) 승차,퇴근시간(17~21) 하차,늦은시간(20~00) 승차,늦은시간(21~02) 하차,점심시간,저녁시간
0,석계역2번출구,2019,01,58,31,0,0,0,0,0,17,0,0
1,한성여객종점,2019,01,683,223,223,31,232,140,72,16,7,-315
2,노원평생학습관,2019,01,404,18,85,0,148,4,54,0,-42,-118
3,서울시립북서울미술관,2019,01,1391,71,321,6,424,16,197,5,-132,-299
4,중계역,2019,01,1713,168,823,6,293,56,108,18,-194,-278
...,...,...,...,...,...,...,...,...,...,...,...,...,...
465032,책향기마을,2019,12,9,1418,5,88,0,629,0,595,165,-426
465033,중앙공원,2019,12,3,619,1,70,0,228,1,219,117,-108
465034,우리은행앞,2019,12,49,2313,3,223,17,961,12,819,389,-611
465035,청석마을8단지,2019,12,10,824,4,71,0,376,4,344,121,-220
465036,교하차고지,2019,12,0,63,0,7,0,13,0,18,15,-6

In [41]:
bus_2019.to_csv('./2019_bus_commuter', index=False)

In [42]:
bus_2020 = pd.read_csv('./2020_bus_commute.csv')
bus_2020

,사용년월,역명,출근시간(04~09) 승차,출근시간(07~10) 하차,퇴근시간(16~20) 승차,퇴근시간(17~21) 하차,점심시간,저녁시간,늦은시간(20~00) 승차,늦은시간(21~02) 하차,총 승차 인원,총 하차 인원,연도
0,202001,창경궁.서울대학교병원,1148,1886,710,247,1843,1142,196,79,2761,3947,2020
1,202001,명륜3가.성대입구,844,1847,1059,896,1914,249,572,176,3202,5472,2020
2,202001,혜화동로터리.여운형활동터,744,1242,288,1417,1464,-279,115,209,1641,5710,2020
3,202001,원남동,849,2528,1460,617,2455,734,399,135,3709,5339,2020
4,202001,종로5가.효제동.김상옥의거터,67,134,555,207,81,-502,244,132,1090,672,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...
468814,202012,우리은행앞,1,284,6,699,340,-281,10,351,26,1567,2020
468815,202012,중앙공원,4,59,1,179,80,-90,0,94,5,435,2020
468816,202012,책향기마을,1,124,2,487,170,-244,0,334,3,1048,2020
468817,202012,교하차고지,52,2,25,2,-5,-24,8,0,102,4,2020
468818,202012,교하차고지,0,17,0,11,19,7,0,9,0,58,2020

In [43]:
bus_2020 = bus_2020.astype({'사용년월' : 'string'})
bus_2020['월'] = bus_2020['사용년월'].str[4:]
bus_2020 = bus_2020.drop('사용년월', axis = 1 )
bus_2020 = bus_2020[['역명', '연도', '월', '총 승차 인원', '총 하차 인원', '출근시간(04~09) 승차', '출근시간(07~10) 하차',
                    '퇴근시간(16~20) 승차', '퇴근시간(17~21) 하차', '늦은시간(20~00) 승차', '늦은시간(21~02) 하차', '점심시간', '저녁시간']]
bus_2020

,역명,연도,월,총 승차 인원,총 하차 인원,출근시간(04~09) 승차,출근시간(07~10) 하차,퇴근시간(16~20) 승차,퇴근시간(17~21) 하차,늦은시간(20~00) 승차,늦은시간(21~02) 하차,점심시간,저녁시간
0,창경궁.서울대학교병원,2020,01,2761,3947,1148,1886,710,247,196,79,1843,1142
1,명륜3가.성대입구,2020,01,3202,5472,844,1847,1059,896,572,176,1914,249
2,혜화동로터리.여운형활동터,2020,01,1641,5710,744,1242,288,1417,115,209,1464,-279
3,원남동,2020,01,3709,5339,849,2528,1460,617,399,135,2455,734
4,종로5가.효제동.김상옥의거터,2020,01,1090,672,67,134,555,207,244,132,81,-502
...,...,...,...,...,...,...,...,...,...,...,...,...,...
468814,우리은행앞,2020,12,26,1567,1,284,6,699,10,351,340,-281
468815,중앙공원,2020,12,5,435,4,59,1,179,0,94,80,-90
468816,책향기마을,2020,12,3,1048,1,124,2,487,0,334,170,-244
468817,교하차고지,2020,12,102,4,52,2,25,2,8,0,-5,-24
468818,교하차고지,2020,12,0,58,0,17,0,11,0,9,19,7

In [44]:
bus_2020.to_csv('./2020_bus_commuter', index=False)

In [ ]:
bus_2021 = pd.read_csv('./2021_bus_commute.csv')
bus_2021 = bus_2019.drop('노선ID', axis=1)
bus_2021

In [22]:
bus_2021 = pd.read_csv('./2021_bus_commute.csv')
#bus_2019.to_csv('2021_bus_commuter.csv')
bus_2021

,사용년월,역명,출근시간(04~09) 승차,출근시간(07~10) 하차,퇴근시간(16~20) 승차,퇴근시간(17~21) 하차,점심시간,저녁시간,늦은시간(20~00) 승차,늦은시간(21~02) 하차,총 승차 인원,총 하차 인원,연도
0,202101,창경궁.서울대학교병원,885,1733,381,174,1704,1310,111,67,1939,3289,2021
1,202101,명륜3가.성대입구,652,1497,454,458,1551,747,201,126,1815,3790,2021
2,202101,혜화동로터리.여운형활동터,584,1014,184,706,1156,285,59,197,1165,3638,2021
3,202101,원남동,701,2119,1016,354,2123,907,275,65,2581,4238,2021
4,202101,종로5가.효제동.김상옥의거터,55,136,481,142,109,-407,173,63,851,498,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...
469356,202112,김포교통(종점가상),0,1,1,2,2,0,1,2,1,11,2021
469357,202112,구미동차고지(기점가상),14,2,19,8,2,-22,5,14,45,32,2021
469358,202112,구미동차고지(종점가상),0,22,0,21,29,7,0,43,1,97,2021
469359,202112,가좌동종점(종점가상),0,44,1,20,50,25,1,12,1,92,2021
469360,202112,가좌동종점(종점가상),0,61,0,10,66,53,0,15,0,105,2021