In [1]:
import pandas as pd

In [6]:
bus_2019 = pd.read_csv('./2019_bus_commuter.csv')
bus_2019

,역명,연도,월,총 승차 인원,총 하차 인원,출근시간(04~09) 승차,출근시간(07~10) 하차,퇴근시간(16~20) 승차,퇴근시간(17~21) 하차,늦은시간(20~00) 승차,늦은시간(21~02) 하차,점심시간,저녁시간
0,석계역2번출구,2019,1,58,31,0,0,0,0,0,17,0,0
1,한성여객종점,2019,1,683,223,223,31,232,140,72,16,7,-315
2,노원평생학습관,2019,1,404,18,85,0,148,4,54,0,-42,-118
3,서울시립북서울미술관,2019,1,1391,71,321,6,424,16,197,5,-132,-299
4,중계역,2019,1,1713,168,823,6,293,56,108,18,-194,-278
...,...,...,...,...,...,...,...,...,...,...,...,...,...
465032,책향기마을,2019,12,9,1418,5,88,0,629,0,595,165,-426
465033,중앙공원,2019,12,3,619,1,70,0,228,1,219,117,-108
465034,우리은행앞,2019,12,49,2313,3,223,17,961,12,819,389,-611
465035,청석마을8단지,2019,12,10,824,4,71,0,376,4,344,121,-220
465036,교하차고지,2019,12,0,63,0,7,0,13,0,18,15,-6

In [7]:
bus_2020 = pd.read_csv('./2020_bus_commuter.csv')
bus_2020

,역명,연도,월,총 승차 인원,총 하차 인원,출근시간(04~09) 승차,출근시간(07~10) 하차,퇴근시간(16~20) 승차,퇴근시간(17~21) 하차,늦은시간(20~00) 승차,늦은시간(21~02) 하차,점심시간,저녁시간
0,창경궁.서울대학교병원,2020,1,2761,3947,1148,1886,710,247,196,79,1843,1142
1,명륜3가.성대입구,2020,1,3202,5472,844,1847,1059,896,572,176,1914,249
2,혜화동로터리.여운형활동터,2020,1,1641,5710,744,1242,288,1417,115,209,1464,-279
3,원남동,2020,1,3709,5339,849,2528,1460,617,399,135,2455,734
4,종로5가.효제동.김상옥의거터,2020,1,1090,672,67,134,555,207,244,132,81,-502
...,...,...,...,...,...,...,...,...,...,...,...,...,...
468814,우리은행앞,2020,12,26,1567,1,284,6,699,10,351,340,-281
468815,중앙공원,2020,12,5,435,4,59,1,179,0,94,80,-90
468816,책향기마을,2020,12,3,1048,1,124,2,487,0,334,170,-244
468817,교하차고지,2020,12,102,4,52,2,25,2,8,0,-5,-24
468818,교하차고지,2020,12,0,58,0,17,0,11,0,9,19,7

In [8]:
bus_2021 = pd.read_csv('./2021_bus_commuter.csv')
bus_2021

,역명,연도,월,총 승차 인원,총 하차 인원,출근시간(04~09) 승차,출근시간(07~10) 하차,퇴근시간(16~20) 승차,퇴근시간(17~21) 하차,늦은시간(20~00) 승차,늦은시간(21~02) 하차,점심시간,저녁시간
0,창경궁.서울대학교병원,2021,1,1939,3289,885,1733,381,174,111,67,1704,1310
1,명륜3가.성대입구,2021,1,1815,3790,652,1497,454,458,201,126,1551,747
2,혜화동로터리.여운형활동터,2021,1,1165,3638,584,1014,184,706,59,197,1156,285
3,원남동,2021,1,2581,4238,701,2119,1016,354,275,65,2123,907
4,종로5가.효제동.김상옥의거터,2021,1,851,498,55,136,481,142,173,63,109,-407
...,...,...,...,...,...,...,...,...,...,...,...,...,...
469356,김포교통(종점가상),2021,12,1,11,0,1,1,2,1,2,2,0
469357,구미동차고지(기점가상),2021,12,45,32,14,2,19,8,5,14,2,-22
469358,구미동차고지(종점가상),2021,12,1,97,0,22,0,21,0,43,29,7
469359,가좌동종점(종점가상),2021,12,1,92,0,44,1,20,1,12,50,25
469360,가좌동종점(종점가상),2021,12,0,105,0,61,0,10,0,15,66,53

In [9]:
len(bus_2019)

465037

In [10]:
bus_2019['역명'].value_counts()

현대아파트             702
노량진역              660
우성아파트             648
서울역버스환승센터         638
연희104고지앞.구성산회관    624
                 ...
목동역목동7단지            1
진흥마트                1
65사단앞               1
덕정초교.진흥마트           1
근로복지공단(가상)          1
Name: 역명, Length: 8234, dtype: int64

In [18]:
bus_2019[bus_2019['월'].isin([1])]

,역명,연도,월,총 승차 인원,총 하차 인원,출근시간(04~09) 승차,출근시간(07~10) 하차,퇴근시간(16~20) 승차,퇴근시간(17~21) 하차,늦은시간(20~00) 승차,늦은시간(21~02) 하차,점심시간,저녁시간
0,석계역2번출구,2019,1,58,31,0,0,0,0,0,17,0,0
1,한성여객종점,2019,1,683,223,223,31,232,140,72,16,7,-315
2,노원평생학습관,2019,1,404,18,85,0,148,4,54,0,-42,-118
3,서울시립북서울미술관,2019,1,1391,71,321,6,424,16,197,5,-132,-299
4,중계역,2019,1,1713,168,823,6,293,56,108,18,-194,-278
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38593,책향기마을,2019,1,5,1735,0,124,1,740,2,708,235,-480
38594,중앙공원,2019,1,4,889,2,77,2,368,1,298,137,-237
38595,우리은행앞,2019,1,55,2467,1,204,21,1031,24,885,356,-662
38596,청석마을8단지,2019,1,3,933,0,62,2,398,0,373,119,-264
38597,교하차고지,2019,1,0,80,0,26,0,18,0,26,35,12

In [20]:
bus_2019_list = []
for i in range(1,12):
    bus_2019_list.append(bus_2019[bus_2019['월'].isin([i])])

bus_2019_list[0]

,역명,연도,월,총 승차 인원,총 하차 인원,출근시간(04~09) 승차,출근시간(07~10) 하차,퇴근시간(16~20) 승차,퇴근시간(17~21) 하차,늦은시간(20~00) 승차,늦은시간(21~02) 하차,점심시간,저녁시간
0,석계역2번출구,2019,1,58,31,0,0,0,0,0,17,0,0
1,한성여객종점,2019,1,683,223,223,31,232,140,72,16,7,-315
2,노원평생학습관,2019,1,404,18,85,0,148,4,54,0,-42,-118
3,서울시립북서울미술관,2019,1,1391,71,321,6,424,16,197,5,-132,-299
4,중계역,2019,1,1713,168,823,6,293,56,108,18,-194,-278
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38593,책향기마을,2019,1,5,1735,0,124,1,740,2,708,235,-480
38594,중앙공원,2019,1,4,889,2,77,2,368,1,298,137,-237
38595,우리은행앞,2019,1,55,2467,1,204,21,1031,24,885,356,-662
38596,청석마을8단지,2019,1,3,933,0,62,2,398,0,373,119,-264
38597,교하차고지,2019,1,0,80,0,26,0,18,0,26,35,12

In [21]:
bus_2019_list[0]['역명'].value_counts()
# 잠시만 생각해보니까 버스가 많을 수록 좋은거 아니야?

서울역버스환승센터     66
현대아파트         60
노량진역          55
우성아파트         54
미아사거리역        52
              ..
상아아파트강남보건소     1
흑석동주민센터        1
흑석한강푸르지오       1
푸르지오상가         1
청석마을8단지        1
Name: 역명, Length: 7921, dtype: int64

In [27]:
bus_2019_nosun = pd.DataFrame(bus_2019_list[0]['역명'].value_counts())
bus_2019_nosun.rename(columns={bus_2019_nosun.columns[0]: "환승 가능한 버스의 수"}, inplace=True)
bus_2019_nosun
#1월부터 12월까지 데이터좀 뽑아주세요.
# 현대아파트? 와.. 정류장 번호로 구별해야한다... 데이터 다시 뽑아야함

            환승 가능한 버스의 수
서울역버스환승센터             66
현대아파트                 60
노량진역                  55
우성아파트                 54
미아사거리역                52
...                  ...
상아아파트강남보건소             1
흑석동주민센터                1
흑석한강푸르지오               1
푸르지오상가                 1
청석마을8단지                1

[7921 rows x 1 columns]

In [30]:
bus_2019_nosun.to_csv('bus_2019_busstop_buscount.csv')

In [ ]:
bus_2020_list = []
for i in range(1,12):
    bus_2020_list.append(bus_2019[bus_2019['월'].isin([i])])

bus_2019_list[0]['역명'].value_counts()

bus_2019_nosun = pd.DataFrame(bus_2019_list[0]['역명'].value_counts())
bus_2019_nosun.rename(columns={bus_2019_nosun.columns[0]: "환승 가능한 버스의 수"}, inplace=True)
bus_2019_nosun

In [ ]:
for i in range(len(bus_2019)):
    for j