In [55]:
import pandas as pd

In [56]:
location = pd.read_csv('./(최종)도로별 위치 정보.csv', encoding='EUC-KR')
location.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3134 entries, 0 to 3133
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   위치         3134 non-null   object
 1   도로명 포함 주소  3134 non-null   object
 2   long       3134 non-null   float64
 3   lat        3134 non-null   float64
dtypes: float64(2), object(2)
memory usage: 98.1+ KB

In [57]:
a = location[location['long'] < 126.75]
a

          위치      도로명 포함 주소        long        lat
90    한림고등학교     충민로 한림고등학교  126.258219  33.397958
176    창전삼거리      서강로 창전삼거리  126.371607  33.265011
226     고덕초교    고덕로79길 고덕초교  126.703130  36.747158
299     용동초교       공릉로 용동초교  126.715630  36.702385
492    88체육관  공항대로41길 88체육관  126.436793  34.812275
735     성내초교      천호옛길 성내초교  126.744435  35.537637
1214    고덕초교    동남로82길 고덕초교  126.703130  36.747158
1638  신트리공원앞    목동동로 신트리공원앞  126.726690  37.506427
1800   동평화시장     청계천로 동평화시장  126.646088  37.466319
2117  신트리공원앞     신정로 신트리공원앞  126.726690  37.506427
2154   방아삼거리     진황도로 방아삼거리  121.516450  31.250610
2233    성내초교       풍성로 성내초교  126.744435  35.537637
2475  신트리공원앞     중앙로 신트리공원앞  126.726690  37.506427
2500   동평화시장    마장로1길 동평화시장  126.646088  37.466319
2769   88체육관     공항대로 88체육관  126.436793  34.812275
2785   보문사입구      지봉로 보문사입구  126.321905  37.688623
2957   창전삼거리      창전로 창전삼거리  126.371607  33.265011

In [58]:
b = location[location['long'] > 127.22]
b

                     위치                 도로명 포함 주소        long        lat
143                성서초교                 잔다리로 성서초교  128.514457  35.851961
223             상수도사업본부               청파로 상수도사업본부  129.072364  35.175111
343               장안중학교                 동일로 장안중학교  129.240845  35.315236
352             봉화환승주차장               신내로 봉화환승주차장  128.732375  36.893093
543                창원초교                  해등로 창원초교  128.619111  35.265738
544              고대구로병원               가마산로 고대구로병원  129.308473  35.557544
586                구룡사앞                 양재대로 구룡사앞  128.049871  37.399293
713                동현초교              공항대로41길 동현초교  129.092831  35.222341
776                 양평역                   선유로 양평역  127.491825  37.492731
777              용암초등학교                소월로 용암초등학교  127.508129  36.614045
838              성원아파트앞                도신로 성원아파트앞  128.448241  35.729996
846                을지병원                한글비석로 을지병원  127.382008  36.355327
956                상암초교                 매봉산로 상암초교  127.731277  34.826211
969               미타사입구                독서당로 미타사입구  127.730303  36.955206
975          대방지하차도(남측)          여의대방로 대방지하차도(남측)  127.766922  35.907757
978                을지병원                  공릉로 을지병원  127.382008  36.355327
1049              문정중학교                 문정로 문정중학교  127.401224  36.355554
1088              양지사거리                 무학로 양지사거리  127.286073  37.233888
1238              정외과의원                 장월로 정외과의원  128.528897  35.829439
1305               구룡사앞                  논현로 구룡사앞  128.049871  37.399293
1314             금천고가차도            가산디지털1로 금천고가차도  127.511807  36.627779
1326              사천교동측                홍제천로 사천교동측  128.064185  35.003779
1343               상암초교                월드컵북로 상암초교  127.731277  34.826211
1347               신동초교                 나루터로 신동초교  127.723136  37.930504
1433                중동교                   증산로 중동교  128.607221  35.841258
1760               동부시장                 중랑역로 동부시장  128.900944  37.760019
1952                중동교                   성암로 중동교  128.607221  35.841258
1969              양지사거리                 마장로 양지사거리  127.286073  37.233888
2036               대청초교              양재대로55길 대청초교  128.650521  35.851256
2088           올림픽공원북2문              성안로 올림픽공원북2문  127.489367  36.630920
2163               삼산교회                 우이천로 삼산교회  129.340833  35.544722
2186                양평역                  선유서로 양평역  127.491825  37.492731
2253             고대구로병원               구로동로 고대구로병원  129.308473  35.557544
2259                양평역              양산로(영등포) 양평역  127.491825  37.492731
2337             성원아파트앞                대림로 성원아파트앞  128.448241  35.729996
2398  양재IC남측(경부선부산방향합류)  경부고속도로 양재IC남측(경부선부산방향합류)  129.075642  35.179554
2428               동부시장               망우로36길 동부시장  128.900944  37.760019
2454               성서초교                  망원로 성서초교  128.514457  35.851961
2498              사천교동측                 성산로 사천교동측  128.064185  35.003779
2514              한국거래소               국제금융로 한국거래소  127.766922  35.907757
2527             금천고가차도                범안로 금천고가차도  127.511807  36.627779
2533             양지근린공원              한글비석로 양지근린공원  127.415901  36.324781
2536              국민생활관                성균관로 국민생활관  127.373219  36.354756
2564               신동초교                  잠원로 신동초교  127.723136  37.930504
2644              사천교동측                 수색로 사천교동측  128.064185  35.003779
2778              문정중학교                 송이로 문정중학교  127.401224  36.355554
2783              국민생활관                 혜화로 국민생활관  127.373219  36.354756
2793            상수도사업본부              서소문로 상수도사업본부  129.072364  35.175111
2829               대청초교                  개포로 대청초교  128.650521  35.851256
2888               창원초교                  노해로 창원초교  128.619111  35.265738
2962               동부시장                  망우로 동부시장  128.900944  37.760019
3087              한국거래소               여의나루로 한국거래소  127.766922  35.907757
3118              궁동삼거리                 오리로 궁동삼거리  127.344503  36.368084

In [59]:
c = location[location['lat'] > 37.73]
c

        위치    도로명 포함 주소        long        lat
1347  신동초교    나루터로 신동초교  127.723136  37.930504
1760  동부시장    중랑역로 동부시장  128.900944  37.760019
2428  동부시장  망우로36길 동부시장  128.900944  37.760019
2564  신동초교     잠원로 신동초교  127.723136  37.930504
2962  동부시장     망우로 동부시장  128.900944  37.760019

In [60]:
d = location[location['lat'] < 37.42]
d

          위치    도로명 포함 주소        long        lat
8     구룡마을입구   선릉로 구룡마을입구  127.138154  37.004771
90    한림고등학교   충민로 한림고등학교  126.258219  33.397958
143     성서초교    잔다리로 성서초교  128.514457  35.851961
176    창전삼거리    서강로 창전삼거리  126.371607  33.265011
177   구룡마을입구  양재대로 구룡마을입구  127.138154  37.004771
...      ...          ...         ...        ...
2888    창원초교     노해로 창원초교  128.619111  35.265738
2949    대지초교    양재천로 대지초교  127.115935  37.329928
2957   창전삼거리    창전로 창전삼거리  126.371607  33.265011
3087   한국거래소  여의나루로 한국거래소  127.766922  35.907757
3118   궁동삼거리    오리로 궁동삼거리  127.344503  36.368084

[82 rows x 4 columns]

In [61]:
result1 = pd.concat([a, b, c, d])
result2 = result1.drop_duplicates()
result2

               위치          도로명 포함 주소        long        lat
90         한림고등학교         충민로 한림고등학교  126.258219  33.397958
176         창전삼거리          서강로 창전삼거리  126.371607  33.265011
226          고덕초교        고덕로79길 고덕초교  126.703130  36.747158
299          용동초교           공릉로 용동초교  126.715630  36.702385
492         88체육관      공항대로41길 88체육관  126.436793  34.812275
...           ...                ...         ...        ...
2388  동부간선올림픽대로진출  분당수서로 동부간선올림픽대로진출  127.118906  37.382699
2421      SG타워아파트     망우로36길 SG타워아파트  127.112391  37.396882
2597         천일초교          구천면로 천일초교  126.978310  37.300539
2649         문정초교           송이로 문정초교  126.921348  35.189273
2949         대지초교          양재천로 대지초교  127.115935  37.329928

[96 rows x 4 columns]

In [62]:
result_reset_inext =result2.reset_index()

In [63]:
result_reset_inext

    index           위치          도로명 포함 주소        long        lat
0      90       한림고등학교         충민로 한림고등학교  126.258219  33.397958
1     176        창전삼거리          서강로 창전삼거리  126.371607  33.265011
2     226         고덕초교        고덕로79길 고덕초교  126.703130  36.747158
3     299         용동초교           공릉로 용동초교  126.715630  36.702385
4     492        88체육관      공항대로41길 88체육관  126.436793  34.812275
..    ...          ...                ...         ...        ...
91   2388  동부간선올림픽대로진출  분당수서로 동부간선올림픽대로진출  127.118906  37.382699
92   2421      SG타워아파트     망우로36길 SG타워아파트  127.112391  37.396882
93   2597         천일초교          구천면로 천일초교  126.978310  37.300539
94   2649         문정초교           송이로 문정초교  126.921348  35.189273
95   2949         대지초교          양재천로 대지초교  127.115935  37.329928

[96 rows x 5 columns]

In [64]:
result_reset_inext = result_reset_inext.drop(['long', 'lat'], axis=1)
result_reset_inext

    index           위치          도로명 포함 주소
0      90       한림고등학교         충민로 한림고등학교
1     176        창전삼거리          서강로 창전삼거리
2     226         고덕초교        고덕로79길 고덕초교
3     299         용동초교           공릉로 용동초교
4     492        88체육관      공항대로41길 88체육관
..    ...          ...                ...
91   2388  동부간선올림픽대로진출  분당수서로 동부간선올림픽대로진출
92   2421      SG타워아파트     망우로36길 SG타워아파트
93   2597         천일초교          구천면로 천일초교
94   2649         문정초교           송이로 문정초교
95   2949         대지초교          양재천로 대지초교

[96 rows x 3 columns]

In [65]:
result_reset_inext['url'] = ""
result_reset_inext['long'] = ""
result_reset_inext['lat'] = ""

In [66]:
result_reset_inext_2 = result_reset_inext

In [67]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver import ActionChains
from bs4 import BeautifulSoup
import time
from tqdm import tqdm

In [68]:
result_index_list = result_reset_inext_2['index'].to_list()
result_address_list =  result_reset_inext_2['위치'].to_list()

In [69]:
result_address_list_setting = []
for i in range(len(result_address_list)):
    result_address_list_split = result_address_list[i].split('(')
    result_address_list_setting.append(result_address_list_split[0])
result_address_list_setting

['한림고등학교',
 '창전삼거리',
 '고덕초교',
 '용동초교',
 '88체육관',
 '성내초교',
 '고덕초교',
 '신트리공원앞',
 '동평화시장',
 '신트리공원앞',
 '방아삼거리',
 '성내초교',
 '신트리공원앞',
 '동평화시장',
 '88체육관',
 '보문사입구',
 '창전삼거리',
 '성서초교',
 '상수도사업본부',
 '장안중학교',
 '봉화환승주차장',
 '창원초교',
 '고대구로병원',
 '구룡사앞',
 '동현초교',
 '양평역',
 '용암초등학교',
 '성원아파트앞',
 '을지병원',
 '상암초교',
 '미타사입구',
 '대방지하차도',
 '을지병원',
 '문정중학교',
 '양지사거리',
 '정외과의원',
 '구룡사앞',
 '금천고가차도',
 '사천교동측',
 '상암초교',
 '신동초교',
 '중동교',
 '동부시장',
 '중동교',
 '양지사거리',
 '대청초교',
 '올림픽공원북2문',
 '삼산교회',
 '양평역',
 '고대구로병원',
 '양평역',
 '성원아파트앞',
 '양재IC남측',
 '동부시장',
 '성서초교',
 '사천교동측',
 '한국거래소',
 '금천고가차도',
 '양지근린공원',
 '국민생활관',
 '신동초교',
 '사천교동측',
 '문정중학교',
 '국민생활관',
 '상수도사업본부',
 '대청초교',
 '창원초교',
 '동부시장',
 '한국거래소',
 '궁동삼거리',
 '구룡마을입구',
 '구룡마을입구',
 '천일초교',
 '삼환아파트',
 '한산초교',
 '한신대',
 '월계1교동측',
 '문정초교',
 '문정초교',
 '명지대입구',
 '도화현대아파트',
 '힐튼',
 '판교JC',
 '삼환아파트',
 '탄천IC진출',
 'SG타워아파트',
 '한산초교',
 '한신대',
 '주공14단지아파트',
 '명지대입구',
 '탄천IC진입',
 '동부간선올림픽대로진출',
 'SG타워아파트',
 '천일초교',
 '문정초교',
 '대지초교']

In [70]:
for i in range(len(result_address_list_setting)):
    result_address_list_setting[i] = result_address_list_setting[i].replace("진입", "")
    result_address_list_setting[i] = "서울 " + result_address_list_setting[i] 
result_address_list_setting

['서울 한림고등학교',
 '서울 창전삼거리',
 '서울 고덕초교',
 '서울 용동초교',
 '서울 88체육관',
 '서울 성내초교',
 '서울 고덕초교',
 '서울 신트리공원앞',
 '서울 동평화시장',
 '서울 신트리공원앞',
 '서울 방아삼거리',
 '서울 성내초교',
 '서울 신트리공원앞',
 '서울 동평화시장',
 '서울 88체육관',
 '서울 보문사입구',
 '서울 창전삼거리',
 '서울 성서초교',
 '서울 상수도사업본부',
 '서울 장안중학교',
 '서울 봉화환승주차장',
 '서울 창원초교',
 '서울 고대구로병원',
 '서울 구룡사앞',
 '서울 동현초교',
 '서울 양평역',
 '서울 용암초등학교',
 '서울 성원아파트앞',
 '서울 을지병원',
 '서울 상암초교',
 '서울 미타사입구',
 '서울 대방지하차도',
 '서울 을지병원',
 '서울 문정중학교',
 '서울 양지사거리',
 '서울 정외과의원',
 '서울 구룡사앞',
 '서울 금천고가차도',
 '서울 사천교동측',
 '서울 상암초교',
 '서울 신동초교',
 '서울 중동교',
 '서울 동부시장',
 '서울 중동교',
 '서울 양지사거리',
 '서울 대청초교',
 '서울 올림픽공원북2문',
 '서울 삼산교회',
 '서울 양평역',
 '서울 고대구로병원',
 '서울 양평역',
 '서울 성원아파트앞',
 '서울 양재IC남측',
 '서울 동부시장',
 '서울 성서초교',
 '서울 사천교동측',
 '서울 한국거래소',
 '서울 금천고가차도',
 '서울 양지근린공원',
 '서울 국민생활관',
 '서울 신동초교',
 '서울 사천교동측',
 '서울 문정중학교',
 '서울 국민생활관',
 '서울 상수도사업본부',
 '서울 대청초교',
 '서울 창원초교',
 '서울 동부시장',
 '서울 한국거래소',
 '서울 궁동삼거리',
 '서울 구룡마을입구',
 '서울 구룡마을입구',
 '서울 천일초교',
 '서울 삼환아파트',
 '서울 한산초교',
 '서울 한신대',
 '서울 월계1교동측',
 '서울 문정초교',
 '서울 문정초교',
 '서울 명지대입구',
 '서울 도화현대아파트',
 '서울 힐튼',
 '서울 판교JC',
 '서울 삼환아파트',
 '서울 탄천IC진출',
 '서울 SG타워아파트',
 '서울 한산초교',
 '서울 한신대',
 '서울 주공14단지아파트',
 '서울 명지대입구',
 '서울 탄천IC',
 '서울 동부간선올림픽대로진출',
 '서울 SG타워아파트',
 '서울 천일초교',
 '서울 문정초교',
 '서울 대지초교']

In [71]:
chrome_options = webdriver.ChromeOptions()

url = "https://map.kakao.com/"
driver = webdriver.Chrome(service=Service("./driver/chromedriver.exe"), options=chrome_options)
driver.get(url)

In [54]:
result_reset_inext_2

    index           위치          도로명 포함 주소                       url long lat
0      90       한림고등학교         충민로 한림고등학교  http://kko.to/3xt5WeoDw-
1     176        창전삼거리          서강로 창전삼거리  http://kko.to/ZD1quwJwEW
2     226         고덕초교        고덕로79길 고덕초교  http://kko.to/UCdjPZm3hv
3     299         용동초교           공릉로 용동초교  http://kko.to/1WaOIMeCPO
4     492        88체육관      공항대로41길 88체육관  http://kko.to/R9235qoXrG
..    ...          ...                ...                       ...  ...  ..
91   2388  동부간선올림픽대로진출  분당수서로 동부간선올림픽대로진출
92   2421      SG타워아파트     망우로36길 SG타워아파트
93   2597         천일초교          구천면로 천일초교
94   2649         문정초교           송이로 문정초교
95   2949         대지초교          양재천로 대지초교

[96 rows x 6 columns]

In [72]:
fail_index = []
adress = []
road_adress = []

for i in tqdm(range(len(result_address_list_setting))):
    css_selector = '''#search\.keyword\.query'''
    search_docs = driver.find_element(By.CSS_SELECTOR, css_selector).send_keys(result_address_list_setting[i] + Keys.ENTER) 
    time.sleep(0.5)
   
    try:
        searh_result = driver.find_element(By.CLASS_NAME, "tit_name").click()
        time.sleep(0.5)


        searh_result = driver.find_element(By.CLASS_NAME, "tit_tool").click()
        time.sleep(0.5)


        searh_result = driver.find_element(By.ID, "tool.map.copyurl").click()
        time.sleep(0.5)

        result_reset_inext_2['url'][i] =  driver.find_element(By.CLASS_NAME, "txt_url").text

        xpath_search_result = '''//*[@id="shareUrl"]/div/div[1]/button/span'''
        search_btn = driver.find_element(By.XPATH, xpath_search_result).click()
        time.sleep(0.5)
    
    except:
        print('카카오로도 해결할 수 없다.')
        fail_index.append(i)
        adress.append(result_reset_inext['위치'][i])
        road_adress.append(result_reset_inext['도로명 포함 주소'][i])
    
    search_docs = driver.find_element(By.CSS_SELECTOR, css_selector).clear()
    time.sleep(0.5)
    
    # 메크로 방지를 위해서 손이 한 번 들어가야함.
    if i == 20:
        print("지도를 터치하세요.")
        time.sleep(10)

result_reset_inext_2

  0%|                                                                                           | 0/96 [00:00<?, ?it/s]C:\Users\김두엽\AppData\Local\Temp\ipykernel_20576\1139806530.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_reset_inext_2['url'][i] =  driver.find_element(By.CLASS_NAME, "txt_url").text
 21%|█████████████████                                                                 | 20/96 [01:04<04:03,  3.21s/it]

지도를 터치하세요.

 25%|████████████████████▌                                                             | 24/96 [01:26<05:05,  4.24s/it]

카카오로도 해결할 수 없다.

 40%|████████████████████████████████▍                                                 | 38/96 [02:09<03:05,  3.19s/it]

카카오로도 해결할 수 없다.

 54%|████████████████████████████████████████████▍                                     | 52/96 [02:52<02:20,  3.18s/it]

카카오로도 해결할 수 없다.

 57%|██████████████████████████████████████████████▉                                   | 55/96 [02:59<01:58,  2.88s/it]

카카오로도 해결할 수 없다.

 64%|████████████████████████████████████████████████████                              | 61/96 [03:16<01:46,  3.05s/it]

카카오로도 해결할 수 없다.

 79%|████████████████████████████████████████████████████████████████▉                 | 76/96 [04:02<01:03,  3.20s/it]

카카오로도 해결할 수 없다.

 85%|██████████████████████████████████████████████████████████████████████            | 82/96 [04:19<00:43,  3.08s/it]

카카오로도 해결할 수 없다.

 88%|███████████████████████████████████████████████████████████████████████▊          | 84/96 [04:23<00:32,  2.70s/it]

카카오로도 해결할 수 없다.

 95%|█████████████████████████████████████████████████████████████████████████████▋    | 91/96 [04:44<00:15,  3.09s/it]

카카오로도 해결할 수 없다.

 99%|█████████████████████████████████████████████████████████████████████████████████▏| 95/96 [04:54<00:02,  2.96s/it]

카카오로도 해결할 수 없다.

100%|██████████████████████████████████████████████████████████████████████████████████| 96/96 [04:56<00:00,  3.08s/it]

    index           위치          도로명 포함 주소                       url long lat
0      90       한림고등학교         충민로 한림고등학교  http://kko.to/VZOfZeX5qr
1     176        창전삼거리          서강로 창전삼거리  http://kko.to/JsWbtaCFww
2     226         고덕초교        고덕로79길 고덕초교  http://kko.to/FNv7BDFW5v
3     299         용동초교           공릉로 용동초교  http://kko.to/E4xPbwa4XC
4     492        88체육관      공항대로41길 88체육관  http://kko.to/PihnCCvFfs
..    ...          ...                ...                       ...  ...  ..
91   2388  동부간선올림픽대로진출  분당수서로 동부간선올림픽대로진출
92   2421      SG타워아파트     망우로36길 SG타워아파트  http://kko.to/UmlcMkxyjq
93   2597         천일초교          구천면로 천일초교  http://kko.to/M__dNoBde-
94   2649         문정초교           송이로 문정초교  http://kko.to/9K5CD3IM7N
95   2949         대지초교          양재천로 대지초교

[96 rows x 6 columns]

In [73]:
#result_reset_inext_2.to_csv('./결측치.csv', encoding='EUC-KR', index=False)

# 이 부분은 수동으로.. ㅠㅠ

In [75]:
result_url = pd.read_csv('./결측치.csv', encoding='EUC-KR')
result_url

    index           위치          도로명 포함 주소                       url  long  lat
0      90       한림고등학교         충민로 한림고등학교  http://kko.to/VZOfZeX5qr   NaN  NaN
1     176        창전삼거리          서강로 창전삼거리  http://kko.to/JsWbtaCFww   NaN  NaN
2     226         고덕초교        고덕로79길 고덕초교  http://kko.to/FNv7BDFW5v   NaN  NaN
3     299         용동초교           공릉로 용동초교  http://kko.to/E4xPbwa4XC   NaN  NaN
4     492        88체육관      공항대로41길 88체육관  http://kko.to/PihnCCvFfs   NaN  NaN
..    ...          ...                ...                       ...   ...  ...
91   2388  동부간선올림픽대로진출  분당수서로 동부간선올림픽대로진출  http://kko.to/LB6Codin1M   NaN  NaN
92   2421      SG타워아파트     망우로36길 SG타워아파트  http://kko.to/UmlcMkxyjq   NaN  NaN
93   2597         천일초교          구천면로 천일초교  http://kko.to/M__dNoBde-   NaN  NaN
94   2649         문정초교           송이로 문정초교  http://kko.to/9K5CD3IM7N   NaN  NaN
95   2949         대지초교          양재천로 대지초교  http://kko.to/LwtpduxBB4   NaN  NaN

[96 rows x 6 columns]

In [76]:
chrome_options = webdriver.ChromeOptions()

url = "https://xn--yq5bk9r.com/blog/map-coordinates"
driver = webdriver.Chrome(service=Service("./driver/chromedriver.exe"), options=chrome_options)
driver.get(url)

In [78]:
url_list = result_url['url']

In [79]:
for i in tqdm(range(len(result_url))):
    css_selector = '''#__next > div > div > main > div.mx-auto.max-w-3xl.px-4.sm\:px-6.xl\:max-w-5xl.xl\:px-0 > article > div > div > div > div.prose.max-w-none.pt-10.pb-8.dark\:prose-dark > div > div.flex.flex-col.space-y-4 > div.flex.flex-col.space-y-4 > input'''
    search_docs = driver.find_element(By.CSS_SELECTOR, css_selector).send_keys(url_list[i]) 
    time.sleep(1.0)

    xpath ='//*[@id="__next"]/div/div/main/div[3]/article/div/div/div/div[1]/div/div[2]/div[1]/button'
    search_btn = driver.find_element(By.XPATH, xpath).click()
    time.sleep(3.0)

    Xpath = '//*[@id="__next"]/div/div/main/div[3]/article/div/div/div/div[1]/div/div[2]/div[2]/div/div[1]/text()[2]'
    text = driver.find_element(By.XPATH, xpath)

    req = driver.page_source
    soup = BeautifulSoup(req, 'html.parser')

    gage = soup.find_all(class_ = "flex flex-col space-y-4")

    gage_text = gage[0].text
    gage_split = gage_text.split(" ")
    result_url['lat'][i] = gage_split[10]
    result_url['long'][i] = gage_split[13]

    search_docs = driver.find_element(By.CSS_SELECTOR, css_selector).clear()
    time.sleep(0.5)
result_url

  0%|                                                                                           | 0/96 [00:00<?, ?it/s]C:\Users\김두엽\AppData\Local\Temp\ipykernel_20576\3490302885.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_url['lat'][i] = gage_split[10]
C:\Users\김두엽\AppData\Local\Temp\ipykernel_20576\3490302885.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_url['long'][i] = gage_split[13]
 98%|████████████████████████████████████████████████████████████████████████████████▎ | 94/96 [07:18<00:09,  4.66s/it]

IndexError: list index out of range

In [80]:
result_url

,index,위치,도로명 포함 주소,url,long,lat
0,90,한림고등학교,충민로 한림고등학교,http://kko.to/VZOfZeX5qr,127.1335777209652,"37.48521893833207,"
1,176,창전삼거리,서강로 창전삼거리,http://kko.to/JsWbtaCFww,126.93285530265706,"37.55175138086673,"
2,226,고덕초교,고덕로79길 고덕초교,http://kko.to/FNv7BDFW5v,127.16652685524116,"37.5611495461388,"
3,299,용동초교,공릉로 용동초교,http://kko.to/E4xPbwa4XC,127.06929691831854,"37.64186006390872,"
4,492,88체육관,공항대로41길 88체육관,http://kko.to/PihnCCvFfs,126.84796031542794,"37.55674700105877,"
...,...,...,...,...,...,...
91,2388,동부간선올림픽대로진출,분당수서로 동부간선올림픽대로진출,http://kko.to/LB6Codin1M,127.1096803380575,"37.48557150653655,"
92,2421,SG타워아파트,망우로36길 SG타워아파트,http://kko.to/UmlcMkxyjq,127.0797465007985,"37.59369385913086,"
93,2597,천일초교,구천면로 천일초교,http://kko.to/M__dNoBde-,127.13330278761967,"37.544260188847275,"
94,2649,문정초교,송이로 문정초교,http://kko.to/9K5CD3IM7N,NaN,NaN
95,2949,대지초교,양재천로 대지초교,http://kko.to/LwtpduxBB4,NaN,NaN

In [81]:
result_url['long'][94] = 127.12905285679582
result_url['lat'][94] =  37.48921362857679

In [82]:
result_url['long'][95] = 127.06468302616136
result_url['lat'][95] =  37.489846654997514

In [83]:
result_url.to_csv('./결측치_위도_경도.csv', index='false')

In [84]:
result_url

,index,위치,도로명 포함 주소,url,long,lat
0,90,한림고등학교,충민로 한림고등학교,http://kko.to/VZOfZeX5qr,127.1335777209652,"37.48521893833207,"
1,176,창전삼거리,서강로 창전삼거리,http://kko.to/JsWbtaCFww,126.93285530265706,"37.55175138086673,"
2,226,고덕초교,고덕로79길 고덕초교,http://kko.to/FNv7BDFW5v,127.16652685524116,"37.5611495461388,"
3,299,용동초교,공릉로 용동초교,http://kko.to/E4xPbwa4XC,127.06929691831854,"37.64186006390872,"
4,492,88체육관,공항대로41길 88체육관,http://kko.to/PihnCCvFfs,126.84796031542794,"37.55674700105877,"
...,...,...,...,...,...,...
91,2388,동부간선올림픽대로진출,분당수서로 동부간선올림픽대로진출,http://kko.to/LB6Codin1M,127.1096803380575,"37.48557150653655,"
92,2421,SG타워아파트,망우로36길 SG타워아파트,http://kko.to/UmlcMkxyjq,127.0797465007985,"37.59369385913086,"
93,2597,천일초교,구천면로 천일초교,http://kko.to/M__dNoBde-,127.13330278761967,"37.544260188847275,"
94,2649,문정초교,송이로 문정초교,http://kko.to/9K5CD3IM7N,127.129053,37.489214
95,2949,대지초교,양재천로 대지초교,http://kko.to/LwtpduxBB4,127.064683,37.489847

In [85]:
location

             위치         도로명 포함 주소        long        lat
0        남부교육청앞      버드나루로 남부교육청앞  126.895507  37.519400
1        혜화동로터리       창경궁로 혜화동로터리  127.001217  37.585533
2           강변역          강변역로 강변역  127.094695  37.535098
3      신한은행암사지점  올림픽로98길 신한은행암사지점  127.129245  37.550553
4       이촌동두산위브    이촌로51길 이촌동두산위브  126.966070  37.516122
...         ...               ...         ...        ...
3129       증산3교         거북골로 증산3교  126.906310  37.580087
3130     잠실3삼거리        삼전로 잠실3삼거리  127.093144  37.510305
3131    마장동주민센터       마장로 마장동주민센터  127.045393  37.566281
3132     대방천사거리       대방천로 대방천사거리  126.920165  37.498530
3133  방화119안전센터    금낭화로 방화119안전센터  126.814263  37.579752

[3134 rows x 4 columns]

In [86]:
result_url_index = result_url['index']

for i in range(len(result_url)):
    location['long'][result_url_index[i]] = result_url['long'][i]
    location['lat'][result_url_index[i]] = result_url['lat'][i]
    
location

C:\Users\김두엽\AppData\Local\Temp\ipykernel_20576\3932356092.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location['long'][result_url_index[i]] = result_url['long'][i]
C:\Users\김두엽\AppData\Local\Temp\ipykernel_20576\3932356092.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  location['lat'][result_url_index[i]] = result_url['lat'][i]

             위치         도로명 포함 주소        long        lat
0        남부교육청앞      버드나루로 남부교육청앞  126.895507    37.5194
1        혜화동로터리       창경궁로 혜화동로터리  127.001217  37.585533
2           강변역          강변역로 강변역  127.094695  37.535098
3      신한은행암사지점  올림픽로98길 신한은행암사지점  127.129245  37.550553
4       이촌동두산위브    이촌로51길 이촌동두산위브   126.96607  37.516122
...         ...               ...         ...        ...
3129       증산3교         거북골로 증산3교   126.90631  37.580087
3130     잠실3삼거리        삼전로 잠실3삼거리  127.093144  37.510305
3131    마장동주민센터       마장로 마장동주민센터  127.045393  37.566281
3132     대방천사거리       대방천로 대방천사거리  126.920165   37.49853
3133  방화119안전센터    금낭화로 방화119안전센터  126.814263  37.579752

[3134 rows x 4 columns]

In [88]:
location.to_csv('./(최종)도로별 위치 정보.csv', index=False, encoding='EUC-KR')

In [87]:
a = location[location['long'] < 126.75]
a

TypeError: '<' not supported between instances of 'str' and 'float'